import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {campaignCloud} from '../functions/creator-campaigns.js';
import {createCreatorCampaign,creatorTwinURL,applyCreatorPresentation} from '../campanas/creador/creator-core.mjs';
import {planInstruction,presentation} from '../campanas/creador/creator-instructions.mjs';
import {compareCampaigns} from '../campanas/creador/creator-cloud-core.mjs';
import {animatedJob} from '../campanas/creador/creator-video.mjs';
import {INSTALLATIONS} from '../campanas/next-step/render.mjs';
const seed='0165a35180d54346ba3c9774bd4882d5',c=createCreatorCampaign(seed);
function database(){const db=new DatabaseSync(':memory:');return {db,prepare(sql){const stmt=db.prepare(sql);let args=[];return {bind(...v){args=v;return this;},async run(){return {meta:{changes:stmt.run(...args).changes}};},async first(){return stmt.get(...args)||null;},async all(){return {results:stmt.all(...args)};}};}};}
const req=(query='',body,origin='https://www.pixeria.com')=>new Request('https://www.pixeria.com/creator-campaigns'+query,{method:body?'POST':'GET',headers:{Origin:origin,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});
test('cloud snapshots are immutable, isolated by owner, versioned and hash checked',async()=>{const AUTH_DB=database(),env={AUTH_DB},alice={email:'alice@fixture.com'},bob={email:'bob@fixture.com'};try{
 const mutation='mutation-00000001';const saved=await campaignCloud(req('',{payload:c,baseVersion:0,mutation}),env,alice);assert.equal(saved.status,201);const d=await saved.json();assert.equal(d.version,1);assert.match(d.hash,/^[a-f0-9]{64}$/);
 assert.equal((await campaignCloud(req('?id='+c.id),env,bob)).status,404);
 assert.deepEqual((await (await campaignCloud(req(),env,bob)).json()).campaigns,[]);
 const recovered=await (await campaignCloud(req('?id='+c.id),env,alice)).json();assert.deepEqual(recovered.payload,c);
 const retry=await (await campaignCloud(req('',{payload:c,baseVersion:0,mutation}),env,alice)).json();assert.equal(retry.replayed,true);assert.equal(retry.version,1);
 const changed={...c,headline:'CAMBIO'};assert.equal((await campaignCloud(req('',{payload:changed,baseVersion:0,mutation:'mutation-00000002'}),env,alice)).status,409);
 assert.equal((await campaignCloud(req('',{payload:changed,baseVersion:1,mutation}),env,alice)).status,409);
 assert.equal((await campaignCloud(req('',{payload:changed,baseVersion:1,mutation:'mutation-00000003'}),env,alice)).status,201);
 const old=await (await campaignCloud(req('?id='+c.id+'&version=1'),env,alice)).json();assert.equal(old.payload.headline,c.headline);assert.equal((await (await campaignCloud(req('?id='+c.id+'&history=1'),env,alice)).json()).versions.length,2);
 assert.deepEqual(compareCampaigns(c,changed),[{field:'headline',before:c.headline,after:'CAMBIO'}]);
 }finally{AUTH_DB.db.close();}});
test('parallel saves from the same version cannot overwrite each other',async()=>{const AUTH_DB=database(),env={AUTH_DB},session={email:'owner@fixture.com'};try{await campaignCloud(req('',{payload:c,baseVersion:0,mutation:'mutation-00000010'}),env,session);const results=await Promise.all([11,12].map(n=>campaignCloud(req('',{payload:{...c,name:'CAMPAIGN '+n},baseVersion:1,mutation:'mutation-000000'+n}),env,session)));assert.deepEqual(results.map(r=>r.status).sort(),[201,409]);assert.equal((await (await campaignCloud(req('?id='+c.id),env,session)).json()).version,2);}finally{AUTH_DB.db.close();}});
test('cloud refuses anonymous, foreign-origin, invalid and secret-bearing writes',async()=>{const AUTH_DB=database(),env={AUTH_DB},session={email:'owner@fixture.com'};try{assert.equal((await campaignCloud(req(),env,null)).status,401);assert.equal((await campaignCloud(req('',{payload:c,baseVersion:0,mutation:'mutation-00000020'},'https://evil.example'),env,session)).status,403);assert.equal((await campaignCloud(req('',{payload:{...c,token:'private'},baseVersion:0,mutation:'mutation-00000021'}),env,session)).status,400);assert.equal((await campaignCloud(req('?id=../../foo'),env,session)).status,400);assert.equal((await campaignCloud(req('?id='+c.id+'&version=-1'),env,session)).status,400);}finally{AUTH_DB.db.close();}});
test('ES/EN instruction plans preserve sources and require review for new background candidates',()=>{for(const text of ['Mantén las zapatillas, cambia el fondo a una ciudad nocturna y prepara tres variantes','Keep the sneakers, change the background to a night city and prepare three variants']){const p=planInstruction(text,c);assert.equal(p.variants,3);assert.equal(p.requiresAI,true);assert.equal(p.approved,false);assert.deepEqual(p.preserve,['product','logo','image','video','seed']);assert.equal(c.backgroundAsset,undefined);}assert.equal(planInstruction('Haz el titular más grande',c).patch.titleScale,1.15);assert.equal(planInstruction('Make the headline smaller',c).patch.titleScale,.85);assert.deepEqual(planInstruction('Titular a “TU NUEVO TEXTO”; CTA a “ENTRA”; acento #00ffcc',c).patch,{headline:'TU NUEVO TEXTO',cta:'ENTRA',accent:'#00ffcc'});assert.throws(()=>planInstruction('borra todo',c),/unsupported/);assert.throws(()=>presentation({video:'https://evil.example'}),/field/);});
test('reviewed presentation round trips to the 360 twin without changing media identity',()=>{const full={...c,mode:'full',image:{id:'image-123'},video:{id:'video-123'},headline:'NEW COPY',titleScale:1.2,backgroundAsset:'background-123'};const u=new URL(creatorTwinURL(full)),result=applyCreatorPresentation(c,u.searchParams);assert.equal(result.headline,'NEW COPY');assert.equal(result.titleScale,1.2);assert.equal(result.backgroundAsset,'background-123');assert.equal(u.searchParams.get('image'),'image-123');assert.throws(()=>applyCreatorPresentation(c,new URLSearchParams({art:'{"video":"https://evil.example"}'})),/field/);});
test('animated export uses native wall crops and common H264 timing for every panel',()=>{let count=0;for(const i of INSTALLATIONS){const j=animatedJob(c,i);count+=j.outputs.length;assert.equal(j.durationSeconds,32);assert.equal(j.args.filter(x=>x==='libx264').length,i.screens.length);for(const [n,s]of i.screens.entries()){assert.match(j.args[j.args.indexOf('-filter_complex')+1],new RegExp(`crop=${s.w}:${s.h}:${s.x}:${s.y}`));assert.equal(j.outputs[n].W,s.w);assert.equal(j.outputs[n].H,s.h);}}assert.equal(count,13);});
