import test from 'node:test';
import assert from 'node:assert/strict';
import {onRequest} from '../functions/creator-ai/[action].js';
import {handleAuth,verifyApiToken} from '../functions/_auth.js';
test('creator endpoints reject missing sessions before any generation',async()=>{const original=globalThis.fetch;let calls=0;globalThis.fetch=async()=>{calls++;throw Error('unexpected-fetch');};try{for(const action of ['image','archive','video','status']){const r=await onRequest({request:new Request('https://admira.studio/creator-ai/'+action,{method:action==='status'?'GET':'POST'}),env:{},params:{action}});assert.equal(r.status,401);}assert.equal(calls,0);}finally{globalThis.fetch=original;}});
test('creator proxy uses the signed session identity and fixed provider parameters',async()=>{
 const env={PIXERIA_SIGNING_KEY:'fixture-signing-key-only',ADMIRA_AGENT_LOGIN_TOKEN:'t'.repeat(64)};
 const session=await handleAuth(new Request('https://admira.studio/auth/agente',{method:'POST',headers:{Authorization:'Bearer '+env.ADMIRA_AGENT_LOGIN_TOKEN}}),env);const cookie=session.headers.get('set-cookie').split(';')[0];
 const original=globalThis.fetch;let calls=0;globalThis.fetch=async(url,options)=>{calls++;assert.equal(url,'https://api.admira.store/xai/image');const identity=await verifyApiToken(options.headers.Authorization.slice(7),env);assert.equal(identity.email,'agentes@silicio.admiranext.com');const body=JSON.parse(options.body);assert.equal(body.n,1);assert.equal(body.model,'grok-imagine-image-pro');assert.equal(body.b64,true);return Response.json({data:[{b64_json:'aW1hZ2U=',mime:'image/png'}]});};
 try{const make=origin=>new Request('https://admira.studio/creator-ai/image',{method:'POST',headers:{Cookie:cookie,Origin:origin,'Content-Type':'application/json'},body:JSON.stringify({prompt:'original sneakers',model:'other',numberOfImages:99})});const blocked=await onRequest({request:make('https://attacker.example'),env,params:{action:'image'}});assert.equal(blocked.status,403);assert.equal(calls,0);const good=await onRequest({request:make('https://admira.studio'),env,params:{action:'image'}});assert.equal(good.status,200);assert.equal(calls,1);}finally{globalThis.fetch=original;}
});
test('completed clips survive later polling without asking the provider to archive twice',async()=>{
 const rows=new Map(),db={prepare(sql){let args=[];return {bind(...values){args=values;return this;},async run(){if(sql.startsWith('INSERT'))rows.set(args[0],{email:args[1],result:args.length===4?args[2]:null});return {};},async first(){return rows.get(args[0]);}};}};
 const env={PIXERIA_SIGNING_KEY:'fixture-signing-key-only',ADMIRA_AGENT_LOGIN_TOKEN:'t'.repeat(64),AUTH_DB:db};
 const session=await handleAuth(new Request('https://admira.studio/auth/agente',{method:'POST',headers:{Authorization:'Bearer '+env.ADMIRA_AGENT_LOGIN_TOKEN}}),env);const cookie=session.headers.get('set-cookie').split(';')[0];let calls=0;
 const original=globalThis.fetch;globalThis.fetch=async url=>{calls++;return Response.json(String(url).endsWith('/xai/video')?{request_id:'request-123'}:{status:'done',archived:true,id:'video-123',url:'https://api.admira.store/stock/asset/video-123'});};
 try{const context=(action,body)=>({request:new Request('https://admira.studio/creator-ai/'+action+(action==='status'?'?request_id=request-123':''),{method:body?'POST':'GET',headers:{Cookie:cookie,Origin:'https://admira.studio','Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})}),env,params:{action}});const started=await onRequest(context('video',{stock_id:'image-123',prompt:'slow motion'}));assert.equal(started.status,200);const first=await (await onRequest(context('status'))).json();assert.equal(first.archived,true);const cached=await (await onRequest(context('status'))).json();assert.deepEqual(cached,first);assert.equal(calls,2);rows.get('request-123').email='different@fixture.example';const denied=await onRequest(context('status'));assert.equal(denied.status,403);assert.equal(calls,2);}finally{globalThis.fetch=original;}
});
