import {mountCampaignCloud} from './creator-cloud.mjs?v=creator-tools-1';
import {planInstruction,presentation} from './creator-instructions.mjs?v=creator-tools-1';
import {exportAnimatedCampaign} from './creator-video.mjs?v=creator-tools-1';
import {INSTALLATIONS} from '../next-step/render.mjs';
import {drawCreatorCampaign} from './creator-render.mjs?v=creator-tools-1';
import {generateBackground} from '../../adaptaciones/ia-core.mjs?v=creator-tools-1';
import {creatorRequest} from './creator-ai.mjs?v=creator-tools-1';
import {FFLATE} from '../../adaptaciones/estancos-core.mjs?v=altadis-ia-20261007';
import {publishAdaptation} from '../../adaptaciones/stock-publish.mjs?v=creator-tools-1';
export function mountCreatorTools({get,getMedia,restore,apply,t,locked}){
 const section=document.createElement('section');section.className='creator-tools';let busy=false,controller=null,files=[],plans=[],selected=-1;
 const heading=document.createElement('h2');heading.textContent=t('Mejorar y preparar esta campaña','Improve and prepare this campaign');section.append(heading);
 const status=document.createElement('p');status.setAttribute('role','status');status.setAttribute('aria-live','polite');
 const textarea=document.createElement('textarea');textarea.rows=3;textarea.placeholder=t('Mantén las zapatillas, cambia el fondo a una ciudad nocturna y prepara tres variantes','Keep the sneakers, change the background to a night city and prepare three variants');textarea.setAttribute('aria-label',t('Instrucciones para la campaña','Campaign instructions'));section.append(textarea);
 const details=document.createElement('details'),sum=document.createElement('summary');sum.textContent=t('Qué puedes pedir','What you can request');const help=document.createElement('p');help.textContent=t('Titular más grande o más pequeño; titular a “TU NUEVO TEXTO”; CTA a “ENTRA”; acento #00ffcc; fondo #101020; fondo a una ciudad nocturna; tres variantes. Las instrucciones que no se entiendan se mostrarán sin aplicarlas.','Larger or smaller headline; headline to “YOUR NEW TEXT”; CTA to “COME IN”; accent #00ffcc; background #101020; background to a night city; three variants. Unsupported instructions are shown without being applied.');details.append(sum,help);section.append(details);
 const changes=document.createElement('pre'),candidates=document.createElement('div');candidates.className='creator-demo-grid';section.append(changes,candidates,status);
 const button=(text,fn)=>{const b=document.createElement('button');b.type='button';b.className='pill';b.textContent=text;b.onclick=()=>void act(fn);section.append(b);return b;};
 const check=()=>busy||locked();async function act(fn){if(check())return;busy=true;section.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn();}catch(e){status.textContent=t('No se completó: ','Could not complete: ')+e.message;}finally{busy=false;section.querySelectorAll('button').forEach(b=>b.disabled=false);}}
 button(t('Preparar cambios','Prepare changes'),async()=>{
  const c=get().campaign,plan=planInstruction(textarea.value,c);plans=[];selected=-1;candidates.replaceChildren();changes.textContent=plan.changes.map(x=>x.field+': '+x.before+' → '+x.after).join('\n')+(plan.background?'\n'+t('Generar fondo: ','Generate background: ')+plan.background+' · '+plan.variants:'');
  if(plan.requiresAI){const media=getMedia();if(!media)throw Error('campaign-media-not-ready');const ref=document.createElement('canvas');ref.width=768;ref.height=Math.round(768*media.image.naturalHeight/media.image.naturalWidth);ref.getContext('2d').drawImage(media.image,0,0,ref.width,ref.height);
   for(let n=0;n<plan.variants;n++){status.textContent=t('Generando fondo ','Generating background ')+(n+1)+'/'+plan.variants;const image=await generateBackground(ref.toDataURL('image/jpeg',.9),{ancho:1920,alto:1080},plan.background+'; distinct variation '+(n+1));const saved=await creatorRequest('archive',{image,seed:c.seed,title:c.name+' · background '+(n+1),prompt:plan.background});if(!saved.ok||!saved.id)throw Error('background-not-archived');plans.push({...plan.patch,backgroundAsset:saved.id});}
  }else{for(let n=0;n<plan.variants;n++)plans.push({...plan.patch,...(n?{accent:['#73d8ff','#ed9bff'][n-1]}:{})});}
  for(const [n,patch]of plans.entries()){const card=document.createElement('button');card.type='button';card.className='campaign-mini';const canvas=document.createElement('canvas');canvas.width=480;let bg=getMedia()?.background;if(patch.backgroundAsset){bg=new Image();bg.crossOrigin='anonymous';bg.src='https://api.admira.store/stock/asset/'+patch.backgroundAsset;await bg.decode();}drawCreatorCampaign(canvas,INSTALLATIONS[0],getMedia()?.image,0,{...c,...patch},bg);const label=document.createElement('span');label.textContent=t('Variante ','Variant ')+(n+1);card.append(canvas,label);card.onclick=()=>{if(check())return;selected=n;for(const [index,other]of [...candidates.children].entries())other.setAttribute('aria-pressed',String(index===n));status.textContent=t('Variante seleccionada. Revisa y aplica para verla en todas las pantallas.','Variant selected. Review and apply to see it on all screens.');};candidates.append(card);}
  status.textContent=t('Cambios preparados. Selecciona una variante para revisarla y aplicarla.','Changes prepared. Select a variant to review and apply.');
 });
 button(t('Aplicar variante revisada','Apply reviewed variant'),async()=>{if(selected<0)throw Error('select-variant');await apply(presentation(plans[selected]));files=[];downloads.replaceChildren();status.textContent=t('Variante aplicada. Comprueba todas las pantallas y el gemelo 360.','Variant applied. Check every screen and the 360 twin.');});
 mountCampaignCloud({host:section,get,restore,t,locked:check});
 const exports=document.createElement('details'),esum=document.createElement('summary');esum.textContent=t('Vídeos animados por pantalla','Animated videos per screen');exports.append(esum);section.append(exports);
 const choices=document.createElement('div');for(const i of INSTALLATIONS){const label=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.value=i.id;input.checked=true;label.append(input,document.createTextNode(i.name[get().campaign.language==='en'?'en':'es']));choices.append(label);}exports.append(choices);
 const review=document.createElement('label'),approved=document.createElement('input');approved.type='checkbox';review.append(approved,document.createTextNode(t('He revisado la composición y sus mapas para esta versión.','I have reviewed this version’s composition and screen maps.')));exports.append(review);
 const downloads=document.createElement('div');exports.append(downloads);
 const exportButton=document.createElement('button');exportButton.className='pill';exportButton.type='button';exportButton.textContent=t('Preparar MP4 seleccionados','Prepare selected MP4s');exports.append(exportButton);
 const cancel=document.createElement('button');cancel.type='button';cancel.className='pill';cancel.textContent=t('Cancelar exportación','Cancel export');cancel.hidden=true;cancel.onclick=()=>controller?.abort();exports.append(cancel);
 exportButton.onclick=()=>void act(async()=>{if(!approved.checked)throw Error('review-required');const selected=[...choices.querySelectorAll('input:checked')].map(x=>INSTALLATIONS.find(i=>i.id===x.value));if(!selected.length)throw Error('select-screens');const c=structuredClone(get().campaign);files=[];downloads.replaceChildren();controller=new AbortController();cancel.hidden=false;cancel.disabled=false;
  try{await exportAnimatedCampaign(c,selected,{signal:controller.signal,onProgress:p=>{status.textContent=(p.index+1)+'/'+p.total+' · '+p.installation+' · '+t(p.phase==='recording'?'Capturando movimiento':'Codificando MP4',p.phase==='recording'?'Capturing motion':'Encoding MP4')+' '+Math.round((p.progress||0)*100)+'%';},onFile:file=>{files.push({...file,campaign:c});const a=document.createElement('a');a.href=URL.createObjectURL(file.blob);a.download=file.filename;a.className='pill';a.textContent='↓ '+file.screen+' · '+file.W+'×'+file.H;downloads.append(a);}});status.textContent=t('Vídeos listos para descargar o publicar en Stock.','Videos ready to download or publish to Stock.');}finally{cancel.hidden=true;controller=null;}
 });
 const publish=document.createElement('button');publish.type='button';publish.className='pill';publish.textContent=t('Publicar vídeos en Stock','Publish videos to Stock');publish.onclick=()=>void act(async()=>{if(!files.length)throw Error('export-first');for(const f of files){if(f.published)continue;status.textContent=t('Publicando ','Publishing ')+f.screen;const result=await publishAdaptation(f.blob,{title:f.campaign.name+' · '+f.screen,originId:f.campaign.id,format:f.installation,width:f.W,height:f.H,duration:f.campaign.seconds,still:false},{tags:['creator-full','campaña-animada',f.screen],externalRef:f.campaign.id,comment:JSON.stringify({schema:'pixeria.creator-video.v1',seed:f.campaign.seed,installation:f.installation,screen:f.screen})});if(!result.ok)throw Error(result.error||'stock-publish');f.published=true;}status.textContent=t('Vídeos publicados en Stock.','Videos published to Stock.');});exports.append(publish);
 const pack=document.createElement('button');pack.type='button';pack.className='pill';pack.textContent=t('Descargar paquete MP4 + campaña','Download MP4 + campaign package');pack.onclick=()=>void act(async()=>{if(!files.length)throw Error('export-first');if(files.reduce((s,f)=>s+f.blob.size,0)>100*1024*1024)throw Error('package-too-large-download-individually');const res=await fetch(FFLATE.url);if(!res.ok)throw Error('zip-download');const bytes=await res.arrayBuffer();const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),b=>b.toString(16).padStart(2,'0')).join('');if(hash!==FFLATE.sha256)throw Error('zip-integrity');const moduleURL=URL.createObjectURL(new Blob([bytes],{type:'text/javascript'}));try{const {zipSync}=await import(moduleURL),entries={};for(const f of files)entries[f.filename]=new Uint8Array(await f.blob.arrayBuffer());entries['campaign.json']=new TextEncoder().encode(JSON.stringify(get(),null,2));entries['outputs.json']=new TextEncoder().encode(JSON.stringify(files.map(({blob,campaign,published,...meta})=>meta)));const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([zipSync(entries,{level:0})],{type:'application/zip'}));a.download=get().campaign.id+'-mp4.zip';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),60000);}finally{URL.revokeObjectURL(moduleURL);}});exports.append(pack);
 const note=document.createElement('p');note.textContent=t('Mantén la pestaña visible durante la captura. Cada maestro empieza en el mismo punto de la composición. MP4 H.264, 25 fps, sin audio; la emisión y sincronización físicas requieren revisión en destino.','Keep this tab visible during capture. Each wall starts at the same composition point. H.264 MP4, 25 fps, no audio; physical playback and synchronisation require on-site review.');exports.append(note);
 return {section,resetReview(){approved.checked=false;files=[];for(const a of downloads.querySelectorAll('a'))URL.revokeObjectURL(a.href);downloads.replaceChildren();},dispose(){controller?.abort();for(const a of downloads.querySelectorAll('a'))URL.revokeObjectURL(a.href);}};
}
