import {cloudIdentity,compareCampaigns} from './creator-cloud-core.mjs?v=creator-tools-2';
export async function cloudRequest(query='',body){const response=await fetch('/creator-campaigns'+query,{method:body?'POST':'GET',credentials:'include',cache:'no-store',headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const data=await response.json();if(!response.ok)throw Error(data.error||'cloud-error');return data;}
export function mountCampaignCloud({host,get,restore,t,locked=()=>false}){
 const section=document.createElement('details'),summary=document.createElement('summary');summary.textContent=t('Campañas en la nube','Cloud campaigns');section.className='creator-cloud';section.append(summary);
 const status=document.createElement('p');status.setAttribute('role','status');let base=0,id='',busy=false,pending=null;
 const button=(text,run)=>{const b=document.createElement('button');b.type='button';b.className='pill';b.textContent=text;b.onclick=()=>void act(run);section.append(b);return b;};
 const select=document.createElement('select'),versions=document.createElement('select'),diff=document.createElement('pre');select.setAttribute('aria-label',t('Campaña en la nube','Cloud campaign'));versions.setAttribute('aria-label',t('Versión en la nube','Cloud version'));section.append(select,versions,diff,status);
 const error=e=>t('No se completó: ','Could not complete: ')+({'session-required':t('inicia sesión.','sign in.'),'open-cloud-version-before-saving':t('esta campaña ya existe en la nube; abre una versión antes de guardar.','this campaign already exists in the cloud; open a version before saving.'),'version-conflict':t('hay una versión más reciente. Abre la última y compara antes de guardar.','a newer version exists. Open the latest and compare before saving.'),'campaign-cloud-unavailable':t('nube no disponible; conserva tu copia local.','cloud unavailable; retain your local copy.')}[e.message]||e.message);
 async function act(fn){if(busy||locked())return;busy=true;section.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn();}catch(e){status.textContent=error(e);}finally{busy=false;section.querySelectorAll('button').forEach(b=>b.disabled=false);}}
 async function refresh(){const d=await cloudRequest();select.replaceChildren(new Option(t('Seleccionar campaña','Select campaign'),''),...d.campaigns.map(c=>new Option(c.name+' · v'+c.version,c.id)));status.textContent=t('Campañas privadas de tu cuenta.','Private campaigns for your account.');}
 button(t('Guardar versión','Save version'),async()=>{const payload=get(),identity=cloudIdentity(payload);if(id!==identity.id){id=identity.id;base=0;try{await cloudRequest('?id='+encodeURIComponent(id));id='';throw Error('open-cloud-version-before-saving');}catch(e){if(e.message!=='campaign-not-found')throw e;}}
  const content=JSON.stringify(payload);if(!pending||pending.content!==content||pending.base!==base)pending={content,base,mutation:crypto.randomUUID()};
  const d=await cloudRequest('',{payload,baseVersion:base,mutation:pending.mutation});base=d.version;pending=null;await refresh();select.value=id;await history();status.textContent=t('Versión guardada en la nube: v','Cloud version saved: v')+base;});
 button(t('Consultar campañas','List campaigns'),refresh);
 async function history(){versions.replaceChildren();if(!select.value)return;const d=await cloudRequest('?id='+encodeURIComponent(select.value)+'&history=1');versions.append(...d.versions.map(v=>new Option('v'+v.version+' · '+v.created_at,v.version)));}
 select.onchange=()=>void act(history);
 button(t('Comparar','Compare'),async()=>{if(!select.value||!versions.value)return;const d=await cloudRequest('?id='+encodeURIComponent(select.value)+'&version='+versions.value);const changes=compareCampaigns(get(),d.payload);diff.textContent=changes.length?changes.map(c=>c.field+': '+JSON.stringify(c.before)+' → '+JSON.stringify(c.after)).join('\n'):t('Sin cambios en la composición.','No composition changes.');});
 button(t('Abrir versión','Open version'),async()=>{if(!select.value||!versions.value)return;const d=await cloudRequest('?id='+encodeURIComponent(select.value)+'&version='+versions.value);const latest=await cloudRequest('?id='+encodeURIComponent(select.value));await restore(d.payload);id=d.id;base=latest.version;pending=null;status.textContent=t('Versión recuperada; revisa antes de exportar.','Version restored; review before exporting.');});
 host.append(section);return {section};
}
