import {orientationPair} from '../../adaptaciones/campaign-entry.mjs?v=creator-tools-1';
import {startCreatorFull} from './full-demo.mjs?v=creator-tools-1';
import {createCreatorCampaign,creatorTwinURL,retainCampaign,CREATOR_HISTORY,STEPS} from './creator-core.mjs?v=creator-tools-1';
import {drawCreatorCampaign} from './creator-render.mjs?v=creator-tools-1';
import {INSTALLATIONS,loadNextStepAssets,createClock} from '../next-step/render.mjs';
const en=new URLSearchParams(location.search).get('lang')==='en'||document.documentElement.lang==='en',t=(a,b)=>en?b:a;
const labels=[t('Brief','Brief'),t('Concepto','Concept'),t('Creatividades','Creatives'),t('Adaptación','Adaptation'),t('Gemelo digital','Digital twin')];
const titles=[t('Primero, el propósito.','First, the purpose.'),t('Una dirección que se reconoce.','A recognisable direction.'),t('La idea ya tiene forma.','The idea takes shape.'),t('Cada pantalla cuenta.','Every screen tells it.'),t('Tu campaña, dentro de Sneaker Xtore.','Your campaign, inside Sneaker Xtore.')];
const texts=[t('Sneaker Xtore · Santa Rosa 19. Invitar a entrar, descubrir la colección y probar un nuevo par. Público urbano, mensaje breve y producto protagonista.','Sneaker Xtore · Santa Rosa 19. Invite people inside, discover the collection and try a new pair. Urban audience, short copy and a product hero.'),t('El nombre, el mensaje, la paleta y el ritmo visual nacen de la semilla de esta campaña. La misma dirección acompaña todo el recorrido.','Name, message, palette and visual rhythm come from this campaign’s seed. The same direction follows the entire journey.'),t('Componemos en este navegador: tipografía, producto, color y movimiento. El producto es la ilustración de NEXT STEP reutilizada; aquí se crea una composición nueva.','Composed in this browser: type, product, colour and movement. The product reuses NEXT STEP artwork; this is a new composition.'),t('Siete composiciones maestras, trece salidas nativas. Jordan comparte un maestro; el LED conserva el hueco de la puerta. Puedes descargar cada PNG y el contrato.','Seven master compositions, thirteen native outputs. Jordan shares one master; the LED keeps its doorway. Download each PNG and the contract.'),t('La misma campaña se aplica a las pantallas del recorrido 360 y del modelo 3D. Arrastra para mirar y cambia de vista.','The same campaign appears on the screens in the 360 tour and 3D model. Drag to look around and change the view.')];
let root,c,step=0,product,loading=false,clock=createClock(),stepStart=0,raf=0,last=0,active=false,selected='landscape',iframe=null,ready=false;
function element(tag,text,className){const el=document.createElement(tag);if(text)el.textContent=text;if(className)el.className=className;return el;}
function button(text,fn,id){const b=element('button',text,'pill');b.type='button';b.onclick=fn;if(id)b.id=id;return b;}
function rows(){try{const r=JSON.parse(localStorage.getItem(CREATOR_HISTORY)||'[]');return Array.isArray(r)?r:[];}catch{return [];}}
function remember(){try{localStorage.setItem(CREATOR_HISTORY,JSON.stringify(retainCampaign(rows(),{...c,step:STEPS[step]})));return true;}catch{return false;}}
function mount(){if(root)return;root=element('section',null,'creator-demo');root.id='creator-demo';root.hidden=true;root.setAttribute('aria-label',t('Demo Creador','Creator demo'));document.querySelector('.adapt-main').prepend(root);const style=element('link');style.rel='stylesheet';style.href='/campanas/creador/demo.css?v=creator-tools-1';document.head.append(style);}
function tellTwin(action){if(iframe?.contentWindow&&ready)iframe.contentWindow.postMessage({type:'admira:creator-control',seed:c.seed,action},'https://www.admira.store');}
function pause(){clock.pause();tellTwin('pause');updateControls();}
function resume(){clock.play();tellTwin('resume');updateControls();}
function updateControls(){if(!root)return;const b=root.querySelector('#creator-pause');if(b)b.textContent=clock.paused?t('▶ Continuar','▶ Resume'):t('Ⅱ Pausar','Ⅱ Pause');const state=root.querySelector('#creator-state');if(state)state.textContent=clock.paused?t('Ensayo pausado','Rehearsal paused'):step===4?(ready?t('Campaña aplicada en el gemelo','Campaign applied in the twin'):t('Cargando el gemelo…','Loading the twin…')):t('Creación en curso','Creation in progress');}
function download(blob,name){const u=URL.createObjectURL(blob),a=element('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),60000);}
function contract(){return {...c,installations:INSTALLATIONS,exportedMedia:'PNG still compositions only; no newly rendered MP4',review:'demo-preview; not approved for physical delivery',web:{studio:location.origin+'/creador/?demo=creador&seed='+c.seed+'&lang='+(en?'en':'es'),twin:creatorTwinURL(c)},steps:STEPS.map((id,n)=>({id,status:n<=step?'shown':'pending'}))};}
function select(i){selected=i.id;renderPreview();}
function renderPreview(){if(!active||!product||step===4)return;const seconds=clock.time(),cv=root.querySelector('#creator-preview');if(cv)drawCreatorCampaign(cv,INSTALLATIONS.find(i=>i.id===selected),product,seconds,c);root.querySelectorAll('canvas[data-installation]').forEach(cv=>drawCreatorCampaign(cv,INSTALLATIONS.find(i=>i.id===cv.dataset.installation),product,seconds,c));}
function openTwin(view='360'){
 if(iframe)iframe.remove();ready=false;iframe=element('iframe');iframe.id='creator-twin';iframe.title=t('Campaña en Sneaker Xtore · gemelo digital','Campaign in Sneaker Xtore · digital twin');iframe.src=creatorTwinURL(c,{view});root.querySelector('#creator-twin-stage').append(iframe);root.querySelector('#creator-open-twin').href=creatorTwinURL(c,{view});updateControls();
}
function render(){
 if(!active)return;if(iframe){iframe.remove();iframe=null;ready=false;}root.replaceChildren();
 const heading=element('div',null,'creator-demo-heading'),copy=element('div');copy.append(element('p','DEMO CREADOR / SNEAKER XTORE','campaign-kicker'),element('h1',c.name),element('p',c.headline));heading.append(copy,button(t('＋ Nueva campaña','＋ New campaign'),()=>void start(), 'creator-new'),button(t('Crear todo con IA','Create full with AI'),()=>void startCreatorFull(null,true)));root.append(heading);
 const nav=element('nav',null,'creator-demo-steps');nav.setAttribute('aria-label',t('Proceso de creación','Creation process'));labels.forEach((label,n)=>{const b=button((n<step?'✓ ':`${n+1} `)+label,()=>go(n));b.setAttribute('aria-current',n===step?'step':'false');nav.append(b);});root.append(nav);
 const tools=element('div',null,'creator-demo-controls');tools.append(button('',()=>clock.paused?resume():pause(),'creator-pause'),button(t('Siguiente →','Next →'),()=>go(Math.min(4,step+1)),'creator-next'),button(t('■ Detener','■ Stop'),stop,'creator-stop'));tools.querySelector('#creator-next').disabled=step===4;const state=element('span',null,'creator-state');state.id='creator-state';state.setAttribute('role','status');tools.append(state);root.append(tools);
 root.append(element('h2',titles[step]),element('p',texts[step],'creator-explanation'));
 if(step<4){
 const stage=element('div',null,'creator-demo-stage'),info=element('aside',null,'creator-demo-brief');info.append(element('p',t('CAMPAÑA','CAMPAIGN'),'campaign-kicker'),element('h3',c.name),element('p',c.headline),element('p',c.cta));
 const palette=element('div',null,'creator-palette');for(const color of [c.background,c.accent,c.secondary,c.foreground]){const swatch=element('span');swatch.style.background=color;swatch.title=color;palette.append(swatch);}info.append(palette,element('p',t('7 configuraciones · 13 pantallas','7 configurations · 13 screens')));stage.append(info);
 if(step<2){const pair=element('div',null,'creator-orientation-pair');pair.setAttribute('aria-label',t('Horizontal y vertical','Landscape and portrait'));for(const i of orientationPair(INSTALLATIONS)){const figure=element('figure'),cv=element('canvas');cv.width=640;cv.dataset.installation=i.id;cv.setAttribute('role','img');const caption=`${i.id==='portrait'?t('Vertical','Portrait'):t('Horizontal','Landscape')} · ${i.width}×${i.height}`;cv.setAttribute('aria-label',c.name+' · '+caption);figure.append(cv,element('figcaption',caption));pair.append(figure);}stage.append(pair);}
 else{const cv=element('canvas');cv.id='creator-preview';cv.width=1100;cv.setAttribute('role','img');cv.setAttribute('aria-label',c.name+' · '+INSTALLATIONS.find(i=>i.id===selected).name[en?'en':'es']);stage.append(cv);}root.append(stage);
 if(step>=2){const tabs=element('div',null,'creator-format-tabs');INSTALLATIONS.forEach(i=>tabs.append(button(i.name[en?'en':'es'],()=>{select(i);tabs.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.textContent===i.name[en?'en':'es'])));})));root.append(tabs);}
 if(step===3){const grid=element('div',null,'creator-demo-grid');for(const i of INSTALLATIONS){const card=element('article'),mini=element('canvas');mini.width=480;mini.dataset.installation=i.id;card.append(mini,element('h3',i.name[en?'en':'es']),element('p',`${i.width} × ${i.height} · ${i.screens.length} ${t('salidas','outputs')}`));for(const s of i.screens)card.append(button('↓ '+s.id,()=>exportPNG(i,s)));grid.append(card);}root.append(grid);}
 }else{
 const links=element('div',null,'creator-demo-controls');links.append(button('360 · '+t('Tienda real','Real store'),()=>openTwin('360')),button('3D · Jordan + LCD',()=>openTwin('3d')));const a=element('a',t('Abrir gemelo completo ↗','Open full twin ↗'),'pill');a.id='creator-open-twin';a.target='_blank';a.rel='noopener';links.append(a);root.append(links);const stage=element('div');stage.id='creator-twin-stage';root.append(stage);openTwin();
 }
 const footer=element('div',null,'creator-demo-footer');footer.append(button('↓ '+t('Guardar contrato','Save contract'),()=>download(new Blob([JSON.stringify(contract(),null,2)],{type:'application/json'}),c.id+'.json')));const history=element('select');history.setAttribute('aria-label',t('Historial de campañas demo','Demo campaign history'));history.append(new Option(t('Campañas demo guardadas','Saved demo campaigns'),''));for(const row of rows())history.append(new Option(row.name+' · '+row.seed.slice(0,8),row.seed));history.onchange=()=>{if(history.value){const row=rows().find(r=>r.seed===history.value);if(row?.mode==='full'){stop();void startCreatorFull(row.seed,false);}else void start(history.value);}};footer.append(history,element('small',t('Composición local de demostración. Ilustración de producto reutilizada. Sin gasto de IA ni publicación en Stock o players.','Local demonstration composition. Reused product artwork. No AI spend or Stock/player publication.')),element('small',t('Geometría especial aproximada. Revisa las piezas antes de una entrega física.','Special geometry is approximate. Review pieces before physical delivery.')));root.append(footer);const id=element('small',c.id,'creator-id');id.dataset.seed=c.seed;root.append(id);updateControls();renderPreview();
}
async function exportPNG(i,s){try{const master=document.createElement('canvas');master.width=i.width;drawCreatorCampaign(master,i,product,clock.time(),c);const cv=document.createElement('canvas');cv.width=s.w;cv.height=s.h;cv.getContext('2d').drawImage(master,s.x,s.y,s.w,s.h,0,0,s.w,s.h);const blob=await new Promise(resolve=>cv.toBlob(resolve,'image/png'));if(!blob)throw Error('png');download(blob,`${c.id}-${s.id}-${s.w}x${s.h}.png`);master.width=master.height=cv.width=cv.height=0;}catch{root.querySelector('#creator-state').textContent=t('No se pudo exportar. Reintenta.','Export failed. Please retry.');}}
function go(n){if(!active)return;step=n;stepStart=clock.time();remember();render();}
function tick(now){if(!active)return;raf=requestAnimationFrame(tick);if(now-last<100||document.hidden)return;last=now;renderPreview();if(!clock.paused&&step<4&&clock.time()-stepStart>8)go(step+1);}
async function start(seed){window.CreatorFull?.stop();mount();if(loading)return t('Cargando elementos…','Loading assets…');loading=true;active=false;cancelAnimationFrame(raf);if(iframe){iframe.remove();iframe=null;}root.hidden=false;document.body.classList.add('creator-demo-active');root.replaceChildren(element('p',t('Cargando producto y tipografía…','Loading product and typography…')));root.scrollIntoView({block:'start'});try{product ||= await loadNextStepAssets(new URL('../next-step/',import.meta.url));c=createCreatorCampaign(seed||crypto.randomUUID().replaceAll('-',''),en);const address=new URL(location.href);address.searchParams.set('demo','creador');address.searchParams.delete('mode');address.searchParams.delete('intent');address.searchParams.set('seed',c.seed);address.searchParams.set('lang',en?'en':'es');window.history.replaceState(null,'',address);step=0;selected='landscape';clock=createClock();stepStart=0;active=true;const saved=remember();render();if(!saved)root.querySelector('#creator-state').textContent=t('Historial lleno: descarga el contrato para conservarla.','History full: download the contract to keep it.');tick(0);return c.name+' · '+t('nueva campaña demo','new demo campaign');}catch(e){active=false;root.replaceChildren(element('p',t('No se pudo crear la demo. Comprueba la conexión y vuelve a intentarlo.','Demo could not start. Check the connection and retry.')),button(t('Reintentar','Retry'),()=>void start()));return t('Demo no iniciada','Demo not started');}finally{loading=false;}}
function stop(){active=false;cancelAnimationFrame(raf);if(iframe){iframe.remove();iframe=null;}if(root)root.hidden=true;document.body.classList.remove('creator-demo-active');return t('Demo detenida. Campaña conservada en su historial.','Demo stopped. Campaign retained in its history.');}
window.addEventListener('message',e=>{if(e.origin!=='https://www.admira.store'||e.source!==iframe?.contentWindow||e.data?.type!=='admira:creator-ready'||e.data.seed!==c?.seed)return;ready=true;updateControls();if(clock.paused)tellTwin('pause');});
window.addEventListener('keydown',e=>{if(e.key==='Escape'&&active)stop();});window.addEventListener('pagehide',stop);
window.CreatorDemo={stopLocal:stop,get active(){return active||window.CreatorFull?.active;},state:()=>active?`${c.name} · ${labels[step]} · ${clock.paused?'Ⅱ':'▶'}`:t('Sin demo activa','No active demo'),run(args=''){const action=args.trim().toLowerCase();if(/^(todo|full)$/.test(action))return startCreatorFull(null,true);if(/^restore [a-f0-9]{32}$/.test(action))return start(action.slice(8));if(window.CreatorFull?.active&&action)return window.CreatorFull.run(action);if(/^(estado|status)$/.test(action))return this.state();if(/^(stop|parar|detener|off)$/.test(action))return stop();if(/^(pausa|pause)$/.test(action)){if(active)pause();return this.state();}if(/^(reanudar|resume|continuar)$/.test(action)){if(active)resume();return this.state();}if(/^(siguiente|next)$/.test(action)){if(active)go(Math.min(4,step+1));return this.state();}if(action&&!/^(nueva|nuevo|new|reiniciar|restart)$/.test(action))return t('Usa /demo creador [todo|nueva|pausa|reanudar|siguiente|estado|stop].','Use /demo creator [full|new|pause|resume|next|status|stop].');return start();}};
const params=new URLSearchParams(location.search);if(params.get('demo')==='creador'||params.get('demo')==='creator'){const seed=params.get('seed');if(params.get('mode')==='full'){const explicit=params.get('intent')==='full';if(explicit){const u=new URL(location.href);u.searchParams.delete('intent');window.history.replaceState(null,'',u);}void startCreatorFull(explicit?null:seed,explicit);}else void start(seed||undefined);}
