import {mountAdmiritoWork} from '../../assets/admirito-work.mjs?v=admirito-work-1';
import {orientationPair} from '../../adaptaciones/campaign-entry.mjs?v=creator-full-5';
import {createCreatorCampaign,creatorTwinURL,retainCampaign,CREATOR_HISTORY} from './creator-core.mjs?v=creator-full-5';
import {drawCreatorCampaign} from './creator-render.mjs?v=creator-full-5';
import {INSTALLATIONS,loadNextStepAssets,createClock} from '../next-step/render.mjs';
import {newFull,readFull,saveFull,runFull} from './creator-ai.mjs?v=creator-full-5';
import {loadCreatorMedia} from './creator-media.mjs?v=creator-full-5';
const en=new URLSearchParams(location.search).get('lang')==='en'||document.documentElement.lang==='en',t=(a,b)=>en?b:a;
const names=[t('Brief','Brief'),t('Concepto','Concept'),t('Imagen + vídeo IA','AI image + video'),t('Adaptación','Adaptation'),t('Gemelo 360','360 twin')];
const phases={brief:0,concept:1,'image-requested':2,'image-ready':2,'archive-requested':2,'image-archived':2,'video-requested':2,'video-pending':2,'media-ready':3,adapted:3,twin:4};
const messages={brief:t('Una campaña nueva para Sneaker Xtore.','A new campaign for Sneaker Xtore.'),concept:t('Definiendo la imagen y el movimiento…','Defining the image and motion…'),'image-requested':t('Generando una imagen nueva con IA…','Generating a new AI image…'),'image-ready':t('Imagen nueva recibida.','New image received.'),'archive-requested':t('Guardando la imagen en la biblioteca…','Saving the image to the library…'),'image-archived':t('Imagen nueva guardada. Preparando el vídeo…','New image saved. Preparing the video…'),'video-requested':t('Solicitando vídeo a partir de esta imagen…','Requesting a video from this image…'),'video-pending':t('El proveedor está generando el vídeo…','The provider is generating the video…'),'media-ready':t('Imagen y vídeo nuevos listos. Preparando pantallas…','New image and video ready. Preparing screens…'),adapted:t('Siete maestros y trece salidas preparados.','Seven masters and thirteen outputs ready.'),twin:t('Cargando la campaña en el gemelo…','Loading the campaign in the twin…')};
let root,job,media,clock=createClock(),active=false,busy=false,paused=false,step=0,selected='landscape',iframe,ready=false,raf=0,last=0,epoch=0,twinTimer,companion;
const el=(tag,text,cls)=>{const x=document.createElement(tag);if(text)x.textContent=text;if(cls)x.className=cls;return x;};
const btn=(text,fn,id)=>{const x=el('button',text,'pill');x.type='button';x.onclick=fn;if(id)x.id=id;return x;};
function rows(){try{return JSON.parse(localStorage.getItem(CREATOR_HISTORY)||'[]');}catch{return [];}}
function campaign(){const localized=createCreatorCampaign(job.seed,en);return {...job.campaign,headline:localized.headline,cta:localized.cta,language:en?'en':'es',product:job.image?.url||null,image:job.image,video:job.video,fullPhase:job.phase,request_id:job.request_id};}
function remember(){try{localStorage.setItem(CREATOR_HISTORY,JSON.stringify(retainCampaign(rows(),campaign())));}catch{}}
function mount(){if(root)return;root=el('section',null,'creator-demo creator-full');root.id='creator-full';root.hidden=true;root.setAttribute('aria-label',t('Demo Creador completo','Full Creator demo'));document.querySelector('.adapt-main').prepend(root);const css=el('link');css.rel='stylesheet';css.href='/campanas/creador/demo.css?v=creator-full-5';document.head.append(css);companion=mountAdmiritoWork({host:()=>root?.querySelector('.creator-orientation-pair')||root,t});}
function state(){if(!active)return t('Sin demo completa activa','No active full demo');if(!job)return t('Preparando campaña completa','Preparing full campaign');if(job.error){if(job.error==='request-result-unknown')return t('Resultado pendiente de confirmar. Esta solicitud no se repetirá automáticamente.','Result awaiting confirmation. This request will not be repeated automatically.');if(job.error==='video-polling-paused')return t('Seguimiento pausado. Pulsa Continuar para consultar el mismo vídeo.','Tracking paused. Click Resume to check the same video.');return t('No se pudo completar este paso: ','This step could not complete: ')+job.error;}if(paused)return t('Recorrido pausado. Las solicitudes enviadas al proveedor pueden terminar.','Walkthrough paused. Requests already sent to the provider may finish.');if(ready&&step===4)return t('Imagen y vídeo IA aplicados en el gemelo 360','AI image and video applied in the 360 twin');return messages[job.phase]+(job.providerStatus?' · '+job.providerStatus:'');}
function paintStatus(){const x=root?.querySelector('#creator-full-state');if(x)x.textContent=state();const p=root?.querySelector('#creator-full-pause');if(p)p.textContent=paused?t('▶ Continuar','▶ Resume'):t('Ⅱ Pausar','Ⅱ Pause');companion?.update({busy:active&&busy&&!job?.error&&['image-requested','video-requested','video-pending'].includes(job?.phase),phase:'create'});}
function tell(action){if(ready&&iframe?.contentWindow)iframe.contentWindow.postMessage({type:'admira:creator-control',seed:job.seed,action},'https://www.admira.store');}
function pause(){paused=true;clock.pause();media?.pause();tell('pause');paintStatus();}
function resume(){paused=false;clock.play();media?.play().catch(e=>{job.error=e.message;paintStatus();});tell('resume');paintStatus();if(!busy&&!['twin','adapted'].includes(job.phase))void pipeline();}
const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function checkpoint(token){while(active&&token===epoch&&paused)await delay(250);if(!active||token!==epoch)throw Error('demo-stopped');}
function rawLink(text,url){const a=el('a',text,'pill');a.href=url;a.target='_blank';a.rel='noopener';return a;}
function exportJSON(){const data={...campaign(),schema:'admira.creator-full.v1',installations:INSTALLATIONS,prompts:job.prompts,events:job.events,history:'browser IndexedDB; separate from Creator drafts',publication:'source image and video archived in Stock; no physical scheduling',outputs:'13 native still PNGs; source AI video; live canvas adaptations in twin'};download(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),job.campaign.id+'-full.json');}
function download(blob,name){const u=URL.createObjectURL(blob),a=el('a');a.href=u;a.download=name;a.hidden=true;document.body.append(a);a.click();setTimeout(()=>{a.remove();URL.revokeObjectURL(u);},60000);}
async function exportPNG(i,s){try{const master=el('canvas');master.width=i.width;drawCreatorCampaign(master,i,media.frame(clock.time()),clock.time(),campaign());const cv=el('canvas');cv.width=s.w;cv.height=s.h;cv.getContext('2d').drawImage(master,s.x,s.y,s.w,s.h,0,0,s.w,s.h);const blob=await new Promise(r=>cv.toBlob(r,'image/png'));if(!blob)throw Error('png-export');download(blob,`${job.campaign.id}-${s.id}-${s.w}x${s.h}.png`);}catch(e){job.error=e.message;paintStatus();}}
function preview(){if(!active||step===4)return;const seconds=clock.time(),source=media?.frame(seconds)||root.querySelector('#creator-full-source');for(const canvas of root.querySelectorAll('canvas[data-installation]'))drawCreatorCampaign(canvas,INSTALLATIONS.find(i=>i.id===canvas.dataset.installation),source,seconds,campaign());}
function openTwin(view='360'){
 if(iframe)iframe.remove();ready=false;clearTimeout(twinTimer);iframe=el('iframe');iframe.id='creator-full-twin';iframe.title=t('Imagen y vídeo IA en Sneaker Xtore 360','AI image and video in Sneaker Xtore 360');iframe.src=creatorTwinURL(campaign(),{view});root.querySelector('#creator-full-twin-stage').append(iframe);root.querySelector('#creator-full-open').href=iframe.src;twinTimer=setTimeout(()=>{if(active&&!ready){job.error='twin-ready-timeout';paintStatus();}},60000);paintStatus();
}
function render(){
 if(!active)return;if(iframe){iframe.remove();iframe=null;}clearTimeout(twinTimer);ready=false;root.replaceChildren();
 const head=el('div',null,'creator-demo-heading'),copy=el('div');copy.append(el('p','DEMO CREADOR / SNEAKER XTORE / IA','campaign-kicker'),el('h1',job.campaign.name),el('p',campaign().headline));const next=btn(t('＋ Nueva campaña con IA','＋ New AI campaign'),()=>void start(null,true),'creator-full-new');next.disabled=busy;head.append(copy,next);root.append(head);
 const nav=el('nav',null,'creator-demo-steps');nav.setAttribute('aria-label',t('Proceso de creación con IA','AI creation process'));const max=phases[job.phase]??2;names.forEach((name,n)=>{const b=btn((n<max?'✓ ':`${n+1} `)+name,()=>{step=n;render();});b.disabled=n>max;b.setAttribute('aria-current',n===step?'step':'false');nav.append(b);});root.append(nav);
 const tools=el('div',null,'creator-demo-controls');tools.append(btn('',()=>paused?resume():pause(),'creator-full-pause'),btn(t('■ Detener','■ Stop'),stop));const stateEl=el('span',null,'creator-state');stateEl.id='creator-full-state';stateEl.setAttribute('role','status');stateEl.setAttribute('aria-live','polite');tools.append(stateEl);root.append(tools);
 root.append(el('h2',names[step]),el('p',step<2?t('Producto protagonista, colección urbana y una dirección visual exclusiva. La IA recibirá el concepto de esta campaña.','A product hero, urban collection and an exclusive visual direction. AI will receive this campaign’s concept.'):step===2?t('Primero generamos una imagen original; después animamos esa misma imagen en un clip nuevo de cinco segundos.','First we generate an original image; then we animate that exact image into a new five-second clip.'):step===3?t('La fotografía y el vídeo comparten siete composiciones con texto independiente y el hueco de la puerta conservado.','The photograph and video share seven compositions with separate copy and the doorway preserved.'):t('Los medios nuevos se reproducen en las pantallas del recorrido 360 y del modelo 3D.','The new media play on the screens in the 360 tour and 3D model.'),'creator-explanation'));
 if(busy&&max===2){const progress=el('progress');progress.setAttribute('aria-label',t('Generación en curso','Generation in progress'));root.append(progress);}
 if(step<3){const assets=el('div',null,'creator-full-assets');if(job.image?.url||job.imageData){const img=el('img');img.id='creator-full-source';img.crossOrigin='anonymous';img.onload=preview;img.src=job.image?.url||job.imageData;img.alt=t('Imagen IA nueva de esta campaña','New AI image for this campaign');assets.append(img);}if(job.video?.url){const video=el('video');video.src=job.video.url;video.controls=true;video.muted=true;video.playsInline=true;assets.append(video);}if(assets.childNodes.length)root.append(assets);const details=el('details'),sum=el('summary',t('Ver instrucciones enviadas a la IA','View instructions sent to AI'));details.append(sum,el('p',job.prompts.image),el('p',job.prompts.video));root.append(details);}
 if(step<3){const pair=el('div',null,'creator-orientation-pair');pair.setAttribute('aria-label',t('Horizontal y vertical','Landscape and portrait'));for(const i of orientationPair(INSTALLATIONS)){const figure=el('figure'),canvas=el('canvas');canvas.width=640;canvas.dataset.installation=i.id;canvas.setAttribute('role','img');const caption=`${i.id==='portrait'?t('Vertical','Portrait'):t('Horizontal','Landscape')} · ${i.width}×${i.height}`;canvas.setAttribute('aria-label',campaign().name+' · '+caption);figure.append(canvas,el('figcaption',caption));pair.append(figure);}root.append(pair);}
 if(step===3&&media){const tabs=el('div',null,'creator-format-tabs');for(const i of INSTALLATIONS)tabs.append(btn(i.name[en?'en':'es'],()=>{selected=i.id;render();}));root.append(tabs);const canvas=el('canvas');canvas.width=1100;canvas.dataset.installation=selected;canvas.className='creator-full-preview';root.append(canvas);const grid=el('div',null,'creator-demo-grid');for(const i of INSTALLATIONS){const card=el('article'),mini=el('canvas');mini.width=480;mini.dataset.installation=i.id;card.append(mini,el('h3',i.name[en?'en':'es']),el('p',`${i.width} × ${i.height}`));for(const s of i.screens)card.append(btn('↓ '+s.id,()=>exportPNG(i,s)));grid.append(card);}root.append(grid);}
 if(step===4&&media){const controls=el('div',null,'creator-demo-controls');controls.append(btn('360 · '+t('Tienda real','Real store'),()=>openTwin()),btn('3D · Jordan + LCD',()=>openTwin('3d')));const a=rawLink(t('Abrir gemelo completo ↗','Open full twin ↗'),'#');a.id='creator-full-open';controls.append(a);root.append(controls);const stage=el('div');stage.id='creator-full-twin-stage';root.append(stage);openTwin();}
 const log=el('ol',null,'creator-full-log');for(const event of job.events){const li=el('li',`${new Date(event.at).toLocaleTimeString(en?'en-GB':'es-ES')} · ${messages[event.phase]||event.phase}`);if(event.phase==='video-pending')li.append(el('small',' · '+event.detail));log.append(li);}root.append(log);
 const foot=el('div',null,'creator-demo-footer');foot.append(btn('↓ '+t('Guardar contrato','Save contract'),exportJSON));if(job.image)foot.append(rawLink(t('Imagen IA ↗','AI image ↗'),job.image.url));if(job.video)foot.append(rawLink(t('Vídeo IA · 5 s ↗','AI video · 5 s ↗'),job.video.url));
 const hist=el('select');hist.setAttribute('aria-label',t('Historial de campañas demo','Demo campaign history'));hist.append(new Option(t('Campañas demo guardadas','Saved demo campaigns'),''));for(const row of rows())hist.append(new Option(row.name+(row.mode==='full'?' · IA':'')+' · '+row.seed.slice(0,8),row.seed));hist.onchange=()=>{if(hist.value){const row=rows().find(r=>r.seed===hist.value);stop();if(row?.mode==='full')void start(row.seed,false);else void window.CreatorDemo.run('restore '+hist.value);}};foot.append(hist);
 foot.append(el('small',t('IA bajo petición: una imagen y un vídeo nuevos por campaña completa. Los originales se guardan en la biblioteca; las adaptaciones son vistas del gemelo y PNG. No programa pantallas físicas.','AI on request: one new image and video per full campaign. Originals are saved in the library; adaptations are twin previews and PNGs. Physical screens are not scheduled.')),el('small',t('Pausar o detener interrumpe el recorrido; una generación enviada al proveedor puede seguir. Volver al historial recupera sus resultados sin repetir la solicitud.','Pause or stop interrupts the walkthrough; a generation already sent to the provider may continue. History recovers its results without repeating the request.')));root.append(foot,el('small',job.campaign.id,'creator-id'));paintStatus();preview();
}
async function prepare(token){if(!media){await loadNextStepAssets(new URL('../next-step/',import.meta.url));const result=await loadCreatorMedia(campaign());if(!active||token!==epoch){result?.dispose();throw Error('demo-stopped');}media=result;}if(paused)media.pause();}
async function pipeline(){if(busy||!active)return;busy=true;const token=epoch;try{render();if(job.phase==='brief')await delay(4000);if(job.phase==='twin'){await prepare(token);step=phases[job.phase];render();return;}
 await runFull(job,{checkpoint:()=>checkpoint(token),alive:()=>active&&token===epoch,delay,changed:()=>{if(!active||token!==epoch)return;step=phases[job.phase]??2;remember();render();}});
 if(!active||token!==epoch||job.error)return;if(['media-ready','adapted'].includes(job.phase)){await prepare(token);await checkpoint(token);job.phase='adapted';job.events.push({phase:'adapted',at:new Date().toISOString()});await saveFull(job);remember();step=3;render();await delay(8000);await checkpoint(token);job.phase='twin';job.events.push({phase:'twin',at:new Date().toISOString()});await saveFull(job);remember();step=4;render();}
 }catch(e){if(active&&token===epoch&&e.message!=='demo-stopped'){job.error=e.message;await saveFull(job);paintStatus();}}finally{if(token===epoch){busy=false;root?.querySelector('progress')?.remove();const b=root?.querySelector('#creator-full-new');if(b)b.disabled=false;paintStatus();}}}
function tick(now){if(!active)return;raf=requestAnimationFrame(tick);if(now-last<100)return;last=now;preview();}
export async function startCreatorFull(seed,explicit=false){return start(seed,explicit);}
async function start(seed,explicit){if(busy)return t('Ya hay una generación en curso.','A generation is already running.');stop();window.CreatorDemo?.stopLocal?.();mount();active=true;paused=false;epoch++;root.hidden=false;document.body.classList.add('creator-demo-active');root.scrollIntoView({block:'start'});try{
 if(seed)job=await readFull(seed);else if(explicit){job=newFull(createCreatorCampaign(crypto.randomUUID().replaceAll('-',''),en));await saveFull(job);}else{root.replaceChildren(el('h1',t('Demo Creador · todo con IA','Creator demo · full AI')),el('p',t('Genera una imagen y un vídeo nuevos y recorre el proceso hasta el gemelo 360.','Generate a new image and video and follow the process into the 360 twin.')),btn(t('Crear campaña completa con IA','Create full campaign with AI'),()=>void start(null,true)));return t('Pulsa Crear campaña completa con IA.','Click Create full campaign with AI.');}
 if(!job)throw Error('saved-campaign-not-found');const address=new URL(location.href);address.searchParams.set('demo','creador');address.searchParams.set('mode','full');address.searchParams.set('seed',job.seed);address.searchParams.delete('intent');window.history.replaceState(null,'',address);clock=createClock();step=phases[job.phase]??2;remember();render();tick(0);
 if(explicit||['video-pending','media-ready','adapted','twin'].includes(job.phase))void pipeline();else{paused=true;job.error=['image-requested','video-requested','archive-requested'].includes(job.phase)?'request-result-unknown':job.error;paintStatus();}return job.campaign.name+' · '+t('campaña completa con IA','full AI campaign');
 }catch(e){busy=false;root.replaceChildren(el('p',t('No se pudo abrir la campaña: ','Campaign could not open: ')+e.message),btn(t('Nueva campaña con IA','New AI campaign'),()=>void start(null,true)));return e.message;}}
function stop(){epoch++;active=false;busy=false;companion?.update({busy:false});cancelAnimationFrame(raf);clearTimeout(twinTimer);iframe?.remove();iframe=null;media?.dispose();media=null;if(root)root.hidden=true;document.body.classList.remove('creator-demo-active');return t('Recorrido detenido; los resultados siguen en el historial.','Walkthrough stopped; results remain in history.');}
window.addEventListener('message',e=>{if(e.origin!=='https://www.admira.store'||e.source!==iframe?.contentWindow||e.data?.seed!==job?.seed)return;if(e.data.type==='admira:creator-ready'){ready=true;clearTimeout(twinTimer);job.error=null;paintStatus();if(paused)tell('pause');}else if(e.data.type==='admira:creator-error'){clearTimeout(twinTimer);job.error=e.data.error||'twin-media-error';paintStatus();}});
window.addEventListener('keydown',e=>{if(e.key==='Escape'&&active)stop();});window.addEventListener('pagehide',stop);
window.CreatorFull={get active(){return active;},start,stop,state,run(action){if(/^(todo|full|nueva|nuevo|new|reiniciar|restart)$/.test(action))return start(null,true);if(/^(estado|status)$/.test(action))return state();if(/^(pausa|pause)$/.test(action))pause();else if(/^(reanudar|resume|continuar)$/.test(action))resume();else if(/^(stop|detener|parar|off)$/.test(action))return stop();return state();}};
