import {CREATOR_KEY,newCampaign,orientationPair} from './campaign-entry.mjs?v=creator-1';
import {DEFAULT_CAMPAIGN,DIRECTIONS,restoreCampaign,planCampaign,validateInstallation,campaignContract,campaignJob} from './campaign-core.mjs?v=campaign-1';
import {drawCampaign,panelCanvas} from './campaign-render.mjs?v=campaign-1';
import {geometry} from './especiales-core.mjs?v=adapter-detail-1';
import {FFLATE} from './estancos-core.mjs?v=altadis-ia-20261007';
import {publishAdaptation} from './stock-publish.mjs?v=composition-1';
import {campaignComposition} from './campaign-composition.mjs?v=composition-1';
let zipLoading=null;
function loadZip(){
 if(!zipLoading)zipLoading=(async()=>{
  const response=await fetch(FFLATE.url,{credentials:'omit'});if(!response.ok)throw Error('zip-download');
  const bytes=await response.arrayBuffer(),digest=await crypto.subtle.digest('SHA-256',bytes),hash=Array.from(new Uint8Array(digest),b=>b.toString(16).padStart(2,'0')).join('');
  if(hash!==FFLATE.sha256)throw Error('zip-integrity');
  const url=URL.createObjectURL(new Blob([bytes],{type:'text/javascript'}));try{return await import(url);}finally{URL.revokeObjectURL(url);}
 })().catch(error=>{zipLoading=null;throw error;});
 return zipLoading;
}
const KEY='pixeria.installation-campaign.v1',HISTORY=KEY+'.history';
const copy=x=>JSON.parse(JSON.stringify(x));
export function mountCampaign({t,queue,openTwin}){
 const creator=/(?:^|\/)creador(?:\/|$)/.test(location.pathname),params=new URLSearchParams(location.search),en=document.documentElement.lang==='en',label=o=>o?.[en?'en':'es']||o?.es||String(o||''),base=document.querySelector('#sec-adapt');
 const launch=document.createElement('div');launch.className='campaign-launch';launch.innerHTML=`<div><b>${t('¿Quieres crear una campaña desde cero?','Want to create a campaign from scratch?')}</b><p>${t('Creador compone producto, marca y mensaje para la instalación. Adaptador transforma contenidos que ya existen.','Creator composes product, brand and message for the installation. Adapter transforms existing content.')}</p></div><a class="pill accent" href="${en?'/en/creador/':'/creador/'}">${t('Ir a Creador','Go to Creator')}</a>`;base.querySelector('.steps').after(launch);
 const root=document.createElement('section');root.id='campaign-workshop';root.hidden=true;root.className='campaign-workshop';
 root.innerHTML=`<div class="campaign-heading"><div><p class="campaign-kicker">${t('CREADOR / CAMPAÑAS PARA PANTALLAS','CREATOR / CAMPAIGNS FOR SCREENS')}</p><h1>${t('Una idea. Cada pantalla cuenta.','One idea. Every screen tells it.')}</h1><p>${t('Crea tu campaña desde cero: producto, marca y mensaje para cada configuración de pantallas.','Create your campaign from scratch: product, brand and message for every screen configuration.')}</p></div>${creator?'':`<button class="pill" type="button" id="campaign-close">← ${t('Adaptador','Adapter')}</button>`}</div>
 <nav class="campaign-flow" aria-label="${t('Recorrido de la campaña','Campaign workflow')}"><span>1 ${t('Contenido','Content')}</span><span>2 ${t('Instalación','Installation')}</span><span>3 ${t('Propuestas','Proposals')}</span><span>4 ${t('Revisar','Review')}</span><span>5 ${t('Exportar','Export')}</span></nav>
 <div class="campaign-tools"><button class="pill accent" id="campaign-new" type="button">＋ ${t('Nueva campaña','New campaign')}</button><a class="pill accent" href="${en?'/en/creador/':'/creador/'}?demo=creador&lang=${en?'en':'es'}">${t('Demo Creador · campaña nueva','Creator demo · new campaign')}</a><a class="pill accent" href="${en?'/en/creador/':'/creador/'}?demo=creador&mode=full&lang=${en?'en':'es'}">${t('Demo Creador · todo con IA','Creator demo · full AI')}</a><a class="pill accent" href="/campanas/next-step/?lang=${en?'en':'es'}">NEXT STEP · ${t('Demo en tienda','Store demo')}</a><button class="pill" id="campaign-demo" type="button">${t('Ejemplo · Sneakers Store','Example · Sneakers Store')}</button><button class="pill" id="campaign-edit" type="button">${t('Editar contenido','Edit content')}</button><button class="pill" id="campaign-twin" type="button">▣ ${t('Ver en gemelo digital','View in digital twin')}</button><button class="pill" id="campaign-geometry" type="button">${t('Ajustar instalación','Adjust installation')}</button><button class="pill" id="campaign-save" type="button">↓ ${t('Guardar campaña','Save campaign')}</button><label class="pill campaign-import">↑ ${t('Abrir campaña','Open campaign')}<input id="campaign-import" type="file" accept="application/json,.json"></label><a class="pill" href="/docs/campanas-instalacion.md" target="_blank">${t('Tutorial','Tutorial')} ↗</a></div>
 <p id="campaign-status" role="status" aria-live="polite"></p><div id="campaign-pair" class="campaign-overview campaign-pair" aria-label="${t('Horizontal y vertical','Landscape and portrait')}" hidden></div><div class="campaign-directions" role="group" aria-label="${t('Dirección creativa','Creative direction')}"></div><div class="campaign-destinations" role="group" aria-label="${t('Instalaciones','Installations')}"></div>
 <div class="campaign-stage"><div class="campaign-stage-head"><div><h2 id="campaign-title"></h2><p id="campaign-dimensions"></p></div><label><input id="campaign-include" type="checkbox" checked> ${t('Incluir en el paquete','Include in package')}</label><label><input id="campaign-guides" type="checkbox" checked> ${t('Zonas seguras y juntas','Safe areas and joints')}</label></div><canvas id="campaign-canvas" role="img"></canvas><p>${t('Con las guías activas puedes arrastrar producto, logo y textos. Los conflictos bloquean la exportación.','With guides enabled you can drag product, logo and copy. Conflicts block export.')}</p><p id="campaign-reference"></p></div>
 <div class="campaign-review"><div><b id="campaign-check"></b><ul id="campaign-issues"></ul><p class="muted">${t('Revisa imagen, copia y legibilidad en el destino. Aprobar autoriza la exportación de esta versión; cualquier cambio exige revisar de nuevo.','Review image, copy and legibility at the destination. Approval enables this version’s export; every change requires a new review.')}</p></div><button class="pill accent" id="campaign-approve" type="button">${t('Aprobar esta pieza','Approve this piece')}</button></div>
 <div id="campaign-overview" class="campaign-overview" aria-label="${t('Revisión de todas las instalaciones','Review all installations')}"></div>
 <div class="campaign-delivery"><div><h2>${t('Paquete de esta dirección','Package for this direction')}</h2><p id="campaign-package-status"></p><p class="muted">${t('PNG y MP4 de composición fija por pantalla, a resolución nativa. Misma duración y 25 fps; la sincronización de players se verifica en la instalación.','Still-composition PNG and MP4 per screen at native resolution. Same duration and 25 fps; player synchronisation must be checked on site.')}</p></div><button class="pill" id="campaign-zip" type="button">↓ ZIP · PNG + ${t('campaña','campaign')}</button><button class="pill accent" id="campaign-mp4" type="button">${t('Preparar MP4 por pantalla','Prepare per-screen MP4')}</button><button class="pill" id="campaign-publish-png" type="button" disabled>${t('Publicar PNG en Stock','Publish PNG to Stock')}</button><button class="pill" id="campaign-publish" type="button" disabled>${t('Publicar MP4 en Stock','Publish MP4 to Stock')}</button></div>`;
 base.before(root);
 const options=document.createElement('section');options.className='campaign-options';options.hidden=true;options.innerHTML=`<h2>${t('Contenido de campaña','Campaign content')}</h2><p>${t('Cada elemento se coloca por separado y se conserva completo.','Each element is placed separately and kept complete.')}</p>
 <label>${t('Nombre','Name')}<input data-field="name" maxlength="100"></label><label>${t('Titular','Headline')}<textarea data-field="headline" maxlength="500" rows="3"></textarea></label><label>${t('Llamada a la acción','Call to action')}<input data-field="cta" maxlength="180"></label><label>${t('Precio · opcional','Price · optional')}<input data-field="price" maxlength="40"></label>
 <label>${t('Producto · PNG, JPG o WebP','Product · PNG, JPG or WebP')}<input id="campaign-product" type="file" accept="image/png,image/jpeg,image/webp"></label><p class="muted">${t('Sustituye los elementos de muestra por tu producto y tu logo. Una imagen con fondo lo conserva.','Replace sample elements with your product and logo. An image with a background keeps it.')}</p><label>${t('Logotipo · PNG, JPG o WebP','Logo · PNG, JPG or WebP')}<input id="campaign-logo" type="file" accept="image/png,image/jpeg,image/webp"></label>
 <label>${t('Fondo','Background')}<input type="color" data-field="background"></label><label>${t('Acento','Accent')}<input type="color" data-field="accent"></label><label>${t('Texto','Copy')}<input type="color" data-field="foreground"></label><label>${t('Duración MP4 · segundos','MP4 duration · seconds')}<input type="number" min="1" max="60" step="1" data-field="seconds"></label><label>${t('Versiones guardadas en este navegador','Versions saved in this browser')}<select id="campaign-history"><option value="">—</option></select></label>`;
 document.querySelector('#cuad-opciones').append(options);
 const advanced=document.createElement('section');advanced.className='campaign-advanced';advanced.hidden=true;advanced.innerHTML=`<h2>${t('Mapa de instalación','Installation map')}</h2><p>${t('Coordenadas en el lienzo de píxeles. La rotación indica el giro físico del panel; la salida se entrega compensada.','Coordinates on the pixel canvas. Rotation describes the physical panel rotation; delivery compensates for it.')}</p><button id="campaign-reset-positions" class="pill" type="button">${t('Restablecer composición de esta pieza','Reset this piece’s composition')}</button><a class="pill" href="${en?'/en/publicidad.html':'/publicidad.html'}">${t('Creatividades por audiencia','Audience creatives')}</a><div class="campaign-map"></div><button id="campaign-apply-map" class="pill" type="button">${t('Aplicar medidas','Apply dimensions')}</button><button id="campaign-altadis" class="pill" type="button">${t('Añadir catálogo Altadis · 29','Add Altadis catalogue · 29')}</button><p>${t('Altadis conserva los perfiles originales y sus atlas de entrega. Aquí se revisa la composición y se entregan archivos por pantalla; cubos y esquinas requieren su mapa físico.','Altadis keeps its original profiles and delivery atlases. Here you review the composition and deliver per-screen files; cubes and corners need their physical map.')}</p>`;
 document.querySelector('#cuad-avanzado-live').append(advanced);
 const storageKey=creator?CREATOR_KEY:KEY;const $=s=>root.querySelector(s),opt=s=>options.querySelector(s);let c=creator?newCampaign(en):copy(DEFAULT_CAMPAIGN),selected='landscape',assets={},approvals={},busy=false,ready=false,exportItems=[],loadTurn=0;
 try{const saved=localStorage.getItem(storageKey);if(saved)c=restoreCampaign(JSON.parse(saved));}catch{}
 if(creator&&params.get('demo')==='sneakers-store')c=copy(DEFAULT_CAMPAIGN);else if(creator&&params.get('nuevo')==='1')c=newCampaign(en);
 if(!c.installations.some(i=>i.id===selected))selected=c.installations[0].id;
 const font=new FontFace('Campaign Sans','url(/adaptaciones/fonts/Montserrat-Variable.ttf)',{weight:'100 900'});document.fonts.add(font);
 const measureCanvas=document.createElement('canvas'),ctx=measureCanvas.getContext('2d');const measure=(text,px)=>{ctx.font=`900 ${px}px 'Campaign Sans',sans-serif`;return ctx.measureText(text).width;};
 const installation=()=>c.installations.find(i=>i.id===selected)||c.installations[0],key=(i,d=c.direction)=>`${i.id}:${d}:r${c.revision}`;
 const say=s=>{$('#campaign-status').textContent=s;};
 function history(){let list=[];try{list=JSON.parse(localStorage.getItem(HISTORY)||'[]');}catch{}return Array.isArray(list)?list:[];}
 function historyMenu(){const select=opt('#campaign-history');select.replaceChildren(new Option('—',''));history().forEach((item,n)=>select.append(new Option(`${item.name} · r${item.revision}`,String(n))));}
 function persist(){try{localStorage.setItem(storageKey,JSON.stringify(c));return true;}catch{say(t('No cabe en el almacenamiento del navegador. Guarda la campaña JSON para conservarla.','Browser storage is full. Save the campaign JSON to keep it.'));return false;}}
 function changed(){c.revision++;approvals={};exportItems=[];persist();render();}
 function fill(){options.querySelectorAll('[data-field]').forEach(el=>el.value=c[el.dataset.field]);historyMenu();}
 const image=async url=>{const im=new Image();im.crossOrigin='anonymous';im.src=url;await im.decode();if(!im.naturalWidth||im.naturalWidth*im.naturalHeight>40000000)throw Error('asset-size');return im;};
 async function loadAssets(){const turn=++loadTurn;ready=false;render();try{const [product,logo]=await Promise.all([image(c.product),image(c.logo),font.load()]);if(turn!==loadTurn)return;assets={product,logo};ready=true;render();}catch{if(turn===loadTurn){ready=false;say(t('No se pudo cargar el producto, el logo o la fuente. Revisa los archivos; exportación bloqueada.','Product, logo or font could not load. Check the files; export is blocked.'));render();}}}
 function reason(code){if(code.startsWith('text-overflow'))return t('El texto completo no cabe legible. Ajusta el mensaje o la instalación.','The complete copy cannot fit legibly. Adjust the message or installation.');return t('Revisa el mapa: medidas, solapes y zonas seguras.','Review the map: dimensions, overlaps and safe areas.');}
 advanced.querySelector('#campaign-reset-positions').onclick=()=>{if(busy)return;for(const k of Object.keys(c.placements||{}))if(k.startsWith(`${selected}:${c.direction}:`))delete c.placements[k];changed();};
 function mapEditor(){const i=installation(),container=advanced.querySelector('.campaign-map');container.replaceChildren();for(const [name,value] of [['width',i.width],['height',i.height]]){const l=document.createElement('label');l.textContent=name==='width'?t('Ancho del lienzo','Canvas width'):t('Alto del lienzo','Canvas height');const input=document.createElement('input');input.type='number';input.min='64';input.max='16384';input.value=value;input.dataset.wall=name;l.append(input);container.append(l);}
  for(const [kind,rows] of [['screens',i.screens],['masks',i.masks||[]]])rows.forEach((s,n)=>{const group=document.createElement('fieldset'),legend=document.createElement('legend');legend.textContent=s.id;group.append(legend);for(const p of ['x','y','w','h',...(kind==='screens'?['rotation']:[])]){const l=document.createElement('label');l.textContent=p==='rotation'?t('Giro','Rotation'):p;const input=document.createElement(p==='rotation'?'select':'input');input.dataset.mapKind=kind;input.dataset.mapIndex=n;input.dataset.mapProperty=p;if(p==='rotation')[0,90,180,270].forEach(r=>input.append(new Option(r+'°',String(r))));else{input.type='number';input.step='2';input.min='0';input.max='16384';}input.value=s[p]||0;l.append(input);group.append(l);}container.append(group);});
 }
 function render(){
  if(root.hidden)return;options.querySelectorAll('input,textarea,select').forEach(e=>e.disabled=busy);advanced.querySelectorAll('input,select,button').forEach(e=>e.disabled=busy);$('#campaign-new').disabled=busy;$('#campaign-demo').disabled=busy;$('#campaign-import').disabled=busy;$('#campaign-save').disabled=busy||!ready;$('#campaign-twin').disabled=busy||!ready;const i=installation(),p=planCampaign(c,i,c.direction,measure),all=c.installations.map(i=>({i,p:planCampaign(c,i,c.direction,measure)}));
  const dirs=$('.campaign-directions');dirs.replaceChildren(...DIRECTIONS.map(d=>{const b=document.createElement('button');b.type='button';b.className='campaign-direction';b.setAttribute('aria-pressed',String(d.id===c.direction));const title=document.createElement('b');title.textContent=label(d);const cv=document.createElement('canvas');cv.width=360;drawCampaign(cv,c,i,planCampaign(c,i,d.id,measure),assets);b.append(title,cv);b.disabled=busy;b.onclick=()=>{if(busy)return;c.direction=d.id;exportItems=[];persist();render();};return b;}));
  const destinations=$('.campaign-destinations');destinations.replaceChildren(...c.installations.map(i=>{const b=document.createElement('button');b.type='button';b.className='pill';b.textContent=label(i.name);b.setAttribute('aria-pressed',String(i.id===selected));b.onclick=()=>{selected=i.id;mapEditor();render();};return b;}));
  $('#campaign-include').checked=i.enabled!==false;$('#campaign-include').disabled=busy;$('#campaign-title').textContent=label(i.name);$('#campaign-dimensions').textContent=`${i.width} × ${i.height} px · ${i.screens.length} ${t('pantallas','screens')} · r${c.revision}`;
  const canvas=$('#campaign-canvas');canvas.width=Math.min(1600,i.width);drawCampaign(canvas,c,i,p,assets,{guides:$('#campaign-guides').checked});canvas.setAttribute('aria-label',`${c.name} · ${label(i.name)} · ${c.direction}`);
  $('#campaign-reference').textContent=i.approximate?t('Referencia aproximada: confirma medidas y distribución antes de instalar. El hueco oscuro representa la puerta.','Approximate reference: confirm measurements and arrangement before installation. The dark opening represents the doorway.'):t('Perfil de píxeles. Comprueba escala física y distancia de lectura en destino.','Pixel profile. Check physical scale and viewing distance on site.');
  $('#campaign-check').textContent=!ready?t('Cargando elementos…','Loading elements…'):!p.valid?t('Necesita ajustes','Adjustments needed'):approvals[key(i)]?t('Pieza aprobada','Piece approved'):t('Composición comprobada · pendiente de tu revisión','Composition checked · awaiting your review');
  $('#campaign-issues').replaceChildren(...p.errors.map(e=>{const li=document.createElement('li');li.textContent=reason(e);return li;}));$('#campaign-approve').disabled=busy||!ready||!p.valid||!!approvals[key(i)];
  const previewCard=({i,p})=>{const card=document.createElement('button');card.type='button';card.className='campaign-mini';card.dataset.installation=i.id;card.setAttribute('aria-label',t('Revisar ','Review ')+label(i.name));const cv=document.createElement('canvas');cv.width=480;drawCampaign(cv,c,i,p,assets);const text=document.createElement('span');text.textContent=`${label(i.name)} · ${i.width}×${i.height} · ${!p.valid?t('ajustar','adjust'):approvals[key(i)]?'✓':t('revisar','review')}${i.enabled===false?' · '+t('fuera del paquete','excluded from package'):''}`;card.append(cv,text);card.disabled=busy;card.onclick=()=>{if(busy)return;selected=i.id;mapEditor();render();$('#campaign-title').scrollIntoView({block:'nearest'});};return card;};
  const paired=creator?orientationPair(c.installations):[],pair=$('#campaign-pair');pair.hidden=!paired.length;pair.replaceChildren(...all.filter(({i})=>paired.includes(i)).map(previewCard));
  const other=all.filter(({i})=>!paired.includes(i)),overview=$('#campaign-overview');overview.hidden=!other.length;overview.replaceChildren(...other.map(previewCard));
  const included=all.filter(({i})=>i.enabled!==false),count=included.filter(({i,p})=>p.valid&&approvals[key(i)]).length,exportable=ready&&included.length>0&&count===included.length;
  $('#campaign-package-status').textContent=`${count}/${included.length} ${t('piezas aprobadas','pieces approved')} · ${c.installations.filter(i=>i.enabled!==false).reduce((n,i)=>n+i.screens.length,0)} ${t('archivos por pantalla','per-screen files')}`;
  for(const id of ['#campaign-zip','#campaign-mp4','#campaign-publish-png'])$(id).disabled=busy||!exportable;
  $('#campaign-publish').disabled=busy||!exportItems.length||!exportItems.every(item=>item.state==='done')||exportItems.every(item=>item.published);
 }
 function open(){root.hidden=false;base.hidden=true;options.hidden=advanced.hidden=false;document.body.classList.add('campaign-active');fill();mapEditor();render();void loadAssets();}
 function close(){root.hidden=true;base.hidden=false;options.hidden=advanced.hidden=true;document.body.classList.remove('campaign-active');}
 const closeButton=$('#campaign-close');if(closeButton)closeButton.onclick=close;
 function begin(value){if(busy)return;c=value;selected=c.installations[0].id;approvals={};exportItems=[];ready=false;assets={};persist();fill();mapEditor();render();void loadAssets();}
 $('#campaign-new').onclick=()=>{if(params.get('demo')==='sneakers-store'||params.has('nuevo')){params.delete('demo');params.delete('nuevo');window.history.replaceState(null,'',location.pathname+(params.size?'?'+params.toString():''));}begin(newCampaign(en));say(t('Campaña nueva. Sube tu producto y tu logo y escribe el mensaje en Editar contenido.','New campaign. Upload your product and logo and write your message in Edit content.'));};
 $('#campaign-demo').onclick=()=>begin(copy(DEFAULT_CAMPAIGN));$('#campaign-edit').onclick=()=>document.body.classList.remove('pf-left-off');$('#campaign-geometry').onclick=()=>document.body.classList.remove('pf-right-off');$('#campaign-guides').onchange=render;$('#campaign-include').onchange=e=>{if(busy)return;installation().enabled=e.target.checked;changed();};
 options.querySelectorAll('[data-field]').forEach(el=>el.oninput=()=>{if(busy)return;const field=el.dataset.field;if(String(c[field])===el.value)return;if(field==='seconds'){const n=Number(el.value);if(!Number.isInteger(n)||n<1||n>60){el.value=c.seconds;return;}c[field]=n;}else{if(field==='headline'&&!el.value.trim()){el.value=c[field];return;}c[field]=el.value;}changed();});
 for(const role of ['product','logo'])opt('#campaign-'+role).onchange=async e=>{const file=e.target.files[0];if(!file||busy)return;if(file.size>8*1048576||!['image/png','image/jpeg','image/webp'].includes(file.type)){say(t('Usa PNG, JPG o WebP de hasta 8 MB.','Use PNG, JPG or WebP up to 8 MB.'));return;}try{const url=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file);});await image(url);c[role]=url;if(role==='product')c.productLabel=file.name;changed();await loadAssets();}catch{say(t('El archivo no es una imagen válida.','The file is not a valid image.'));}e.target.value='';};
 let drag=null;const stageCanvas=$('#campaign-canvas');function point(e){const r=stageCanvas.getBoundingClientRect(),i=installation();return{x:(e.clientX-r.left)/r.width*i.width,y:(e.clientY-r.top)/r.height*i.height};}
 stageCanvas.onpointerdown=e=>{if(busy||!ready||!$('#campaign-guides').checked)return;const p=point(e),plan=planCampaign(c,installation(),c.direction,measure),layer=[...plan.layers].reverse().find(l=>l.role!=='echo'&&p.x>=l.x&&p.x<=l.x+l.w&&p.y>=l.y&&p.y<=l.y+l.h);if(!layer)return;e.preventDefault();stageCanvas.setPointerCapture(e.pointerId);drag={role:layer.role,start:p,rect:{x:layer.x,y:layer.y,w:layer.w,h:layer.h},pointer:e.pointerId};};
 stageCanvas.onpointermove=e=>{if(!drag)return;const p=point(e),i=installation(),r=drag.rect;c.placements||={};c.placements[`${i.id}:${c.direction}:${drag.role}`]={x:(r.x+p.x-drag.start.x)/i.width,y:(r.y+p.y-drag.start.y)/i.height,w:r.w/i.width,h:r.h/i.height};render();};
 const endDrag=()=>{if(!drag)return;drag=null;changed();};stageCanvas.onpointerup=endDrag;stageCanvas.onpointercancel=endDrag;
 $('#campaign-approve').onclick=()=>{const i=installation(),p=planCampaign(c,i,c.direction,measure);if(ready&&p.valid){approvals[key(i)]={revision:c.revision,direction:c.direction,reviewedAt:new Date().toISOString()};render();}};
 function download(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),60000);}
 function portable(){const out=copy(c);for(const role of ['product','logo']){const image=assets[role],cv=document.createElement('canvas');cv.width=image.naturalWidth;cv.height=image.naturalHeight;cv.getContext('2d').drawImage(image,0,0);out[role]=cv.toDataURL('image/png');cv.width=cv.height=0;}return out;}
 function save(){if(!ready||busy)return;const contract=campaignContract(portable(),approvals);download(new Blob([JSON.stringify(contract,null,2)],{type:'application/json'}),`${c.id}-r${c.revision}.json`);try{const rows=history();rows.unshift(copy(c));localStorage.setItem(HISTORY,JSON.stringify(rows.slice(0,5)));historyMenu();say(t('Campaña guardada con elementos, mapas y revisiones.','Campaign saved with elements, maps and reviews.'));}catch{say(t('JSON descargado; el historial del navegador está lleno.','JSON downloaded; browser history is full.'));}}
 $('#campaign-save').onclick=save;
 async function replace(value){if(busy)return;const next=restoreCampaign(value);c=next;c.revision++;approvals={};exportItems=[];selected=c.installations[0].id;persist();fill();mapEditor();await loadAssets();say(t('Campaña abierta. Revisa y aprueba sus piezas.','Campaign opened. Review and approve its pieces.'));}
 $('#campaign-import').onchange=async e=>{const f=e.target.files[0];try{if(!f||f.size>20000000)throw Error('size');const value=JSON.parse(await f.text());await replace(value.campaign||value);}catch{say(t('Campaña no válida: conserva el esquema, los elementos y los mapas.','Invalid campaign: keep the schema, elements and maps.'));}e.target.value='';};
 opt('#campaign-history').onchange=e=>{if(e.target.value!=='')void replace(history()[Number(e.target.value)]).catch(()=>say(t('No se pudo abrir esta versión.','Could not open this version.')));};
 advanced.querySelector('#campaign-apply-map').onclick=()=>{if(busy)return;const i=copy(installation());advanced.querySelectorAll('[data-wall]').forEach(el=>i[el.dataset.wall]=Number(el.value));advanced.querySelectorAll('[data-map-kind]').forEach(el=>i[el.dataset.mapKind][Number(el.dataset.mapIndex)][el.dataset.mapProperty]=Number(el.value));const errors=validateInstallation(i);if(errors.length){say(reason(errors[0]));return;}i.approximate=true;c.installations=c.installations.map(x=>x.id===i.id?i:x);changed();mapEditor();};
 advanced.querySelector('#campaign-altadis').onclick=async()=>{if(busy)return;busy=true;render();try{const [a,b]=await Promise.all(['/adaptaciones/perfil-cliente-18.json','/adaptaciones/perfil-cliente-especiales.json'].map(async u=>{const r=await fetch(u);if(!r.ok)throw Error('catalogue');return r.json();}));const list=a.formats.map(f=>({id:f.id,name:{es:f.nombre,en:f.nombre},width:f.custom[0],height:f.custom[1],approximate:true,screens:[{id:f.id,x:0,y:0,w:f.custom[0],h:f.custom[1],rotation:0}]}));for(const f of b.layouts){const g=geometry(f);list.push({id:f.id,name:{es:f.nombre,en:f.nombre},width:g.pared.ancho,height:g.pared.alto,approximate:true,screens:g.segments.map(s=>({id:`${f.id}-${s.n}`,...s.wall,rotation:0})),sourceAtlas:{width:f.entrega[0],height:f.entrega[1]}});}if(list.some(i=>validateInstallation(i).length))throw Error('catalogue');const ids=new Set(c.installations.map(i=>i.id));c.installations.push(...list.filter(i=>!ids.has(i.id)).map(i=>({...i,enabled:false})));changed();say(t('29 perfiles Altadis añadidos, sin incluir aún en el paquete. Selecciona los que vas a preparar. Los formatos que no admitan la copia completa quedan bloqueados para ajustar. Cubos y esquinas requieren confirmar su mapa.','29 Altadis profiles added, initially excluded from the package. Select the ones to prepare. Formats that cannot fit complete copy remain blocked for adjustment. Cubes and corners need a confirmed map.'));}catch{say(t('No se pudo cargar el catálogo; conservamos la campaña.','Catalogue could not load; campaign retained.'));}finally{busy=false;render();}};
 const blob=canvas=>new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('canvas')),'image/png'));
 function master(i,campaign=c){const p=planCampaign(campaign,i,campaign.direction,measure);if(!ready||!p.valid||!approvals[`${i.id}:${campaign.direction}:r${campaign.revision}`])throw Error('review');const cv=document.createElement('canvas');cv.width=i.width;return drawCampaign(cv,campaign,i,p,assets);}
 async function deliver(kind){
  const included=c.installations.filter(i=>i.enabled!==false);
  if(busy||!ready||!included.length||included.some(i=>!approvals[key(i)]||!planCampaign(c,i,c.direction,measure).valid))return;
  busy=true;render();const snapshot=copy(c),contract=campaignContract(snapshot);
  try{
   if(kind==='mp4')for(const i of snapshot.installations.filter(i=>i.enabled!==false))for(const s of i.screens)campaignJob(snapshot,i,s);
   const files={};
   for(const i of snapshot.installations.filter(i=>i.enabled!==false)){
    const wall=master(i,snapshot);
    try{for(const s of i.screens){
     const cv=panelCanvas(wall,s),width=cv.width,height=cv.height;let png;
     try{png=await blob(cv);}finally{cv.width=cv.height=0;}
     const name=`${snapshot.id}-${i.id}-${snapshot.direction}-${s.id}-r${snapshot.revision}-${width}x${height}.png`;
     if(kind==='png')files[name]=new Uint8Array(await png.arrayBuffer());
     else if(kind==='stock-png'){
      const derived=contract.derived.find(d=>d.installation===i.id&&d.screen===s.id),
       composition=campaignComposition(snapshot,i,s,planCampaign(snapshot,i,snapshot.direction,measure),{mediaType:'image'}),
       result=await publishAdaptation(png,{type:'image',title:`${snapshot.name} · ${i.id} · ${s.id} · ${snapshot.direction} · r${snapshot.revision}`,originId:`${snapshot.id}:r${snapshot.revision}`,client:null,format:i.id,width,height,still:true},{
        tags:['adaptación','imagen-fija','creador',...derived.tags],externalRef:`${snapshot.id}:r${snapshot.revision}`,composition,
        comment:JSON.stringify({schema:DEFAULT_CAMPAIGN.schema,campaign:snapshot.id,revision:snapshot.revision,installation:i.id,screen:s.id,direction:snapshot.direction})
       });
      if(!result.ok)throw Error(result.error||'stock');
     }else{
      const job=campaignJob(snapshot,i,s),item=queue.add({label:`${snapshot.name} · ${label(i.name)} · ${s.id}`,sub:`${job.W}×${job.H} · ${snapshot.seconds} s · r${snapshot.revision}`,sourceURL:URL.createObjectURL(png),job,campaign:{revision:snapshot.revision,installation:i.id,screen:s.id,direction:snapshot.direction,contract,name:snapshot.name,seconds:snapshot.seconds}});exportItems.push(item);
     }
    }}finally{wall.width=wall.height=0;}
   }
   if(kind==='png'){
    files['campaign.json']=new TextEncoder().encode(JSON.stringify(campaignContract(portable(),approvals),null,2));const {zipSync}=await loadZip();download(new Blob([zipSync(files,{level:0})],{type:'application/zip'}),`${snapshot.id}-${snapshot.direction}-r${snapshot.revision}.zip`);say(t('Paquete PNG y campaña descargados.','PNG package and campaign downloaded.'));
   }else if(kind==='stock-png')say(t('PNG publicados en Stock con su texto y composición, a resolución nativa por pantalla.','PNGs published to Stock with their copy and composition, at each screen’s native resolution.'));
   else say(t('MP4 en cola. Podrás descargarlos y publicarlos en Stock cuando terminen.','MP4 queued. You can download and publish them to Stock when complete.'));
  }catch(e){say(kind==='stock-png'?t('La publicación PNG no se completó. La campaña y sus aprobaciones se conservan para reintentar.','PNG publication did not complete. The campaign and its approvals are retained for retry.'):e.message==='even-resolution'?t('MP4 requiere medidas pares. Ajusta los paneles.','MP4 requires even dimensions. Adjust the panels.'):t('No se pudo preparar el paquete. Revisa las piezas y los mapas.','Package could not be prepared. Review pieces and maps.'));}finally{busy=false;render();}
 }
 $('#campaign-zip').onclick=()=>void deliver('png');$('#campaign-mp4').onclick=()=>{exportItems=[];void deliver('mp4');};$('#campaign-publish-png').onclick=()=>deliver('stock-png');
 $('#campaign-publish').onclick=async()=>{if(busy||!exportItems.length||!exportItems.every(i=>i.state==='done'))return;busy=true;render();try{for(const item of exportItems){if(item.published)continue;const m=item.campaign;for(const file of item.files){const p=m.contract.derived.find(d=>d.installation===m.installation&&d.screen===m.screen),installation=m.contract.campaign.installations.find(i=>i.id===m.installation),screen=installation.screens.find(s=>s.id===m.screen),composition=campaignComposition(m.contract.campaign,installation,screen,planCampaign(m.contract.campaign,installation,m.direction,measure)),result=await publishAdaptation(file.blob,{title:`${m.name} · ${m.installation} · ${m.screen} · ${m.direction} · r${m.revision}`,originId:`${m.contract.campaign.id}:r${m.revision}`,client:null,format:m.installation,width:file.output.W,height:file.output.H,duration:m.seconds,still:true},{tags:['adaptación','imagen-fija',...p.tags],externalRef:`${m.contract.campaign.id}:r${m.revision}`,composition,comment:JSON.stringify({schema:DEFAULT_CAMPAIGN.schema,campaign:m.contract.campaign.id,revision:m.revision,installation:m.installation,screen:m.screen,direction:m.direction})});if(!result.ok)throw Error(result.error||'stock');item.published=true;queue.note(item,t('Publicado en Stock','Published to Stock')+` · ${result.num||result.id}`);}}say(t('MP4 publicados con etiquetas de campaña, instalación y pantalla.','MP4 published with campaign, installation and screen tags.'));}catch{say(t('La publicación no se completó. Los archivos siguen en la cola para descargar o reintentar.','Publishing did not complete. Files remain in the queue to download or retry.'));}finally{busy=false;render();}};
 // Queue notifications update only the publish control; do not repaint the whole workshop per frame.
 function exportChanged(){if(root.hidden)return;$('#campaign-publish').disabled=busy||!exportItems.length||!exportItems.every(i=>i.state==='done')||exportItems.every(i=>i.published);}
 if(creator||params.get('taller')==='sneakers-store'){open();if(creator){persist();if(params.get('demo')==='sneakers-store'||params.has('nuevo')){params.delete('demo');params.delete('nuevo');window.history.replaceState(null,'',location.pathname+(params.size?'?'+params.toString():''));}}}
 function formats(){return c.installations.map(i=>({id:i.id,nombre:label(i.name),custom:[i.width,i.height],installation:i}));}
 $('#campaign-twin').onclick=()=>{if(ready)openTwin?.(formats().find(f=>f.id===selected));};
 return{open,exportChanged,active:()=>!root.hidden,ready:()=>ready,formats,draw:(cv,f)=>{if(!f.installation)return false;drawCampaign(cv,c,f.installation,planCampaign(c,f.installation,c.direction,measure),assets);return true;}};
}
