import {twinGeometry} from './gemelo-core.mjs';

// Same Better renderer/model family as Xpaces. Media belongs to the editor;
// one master frame supplies the selected physical layout and AI background.
export function mountTwin(h){
  const t=h.t,modal=document.createElement('dialog');modal.className='adapter-twin';modal.setAttribute('aria-labelledby','twin-title');
  modal.innerHTML=`<header><div><h2 id="twin-title">${t('Gemelo digital · Estanco · Better','Digital twin · Shop · Better')}</h2><p id="twin-format"></p></div><button type="button" class="pill twin-close" aria-label="${t('Cerrar gemelo digital','Close digital twin')}">✕</button></header>
  <div class="twin-tools"><label>${t('Estanco','Shop')} <select id="twin-shop"></select></label><label>${t('Escenario','Scenario')} <select id="twin-scenario"><option value="flat">${t('Pared plana','Flat wall')}</option><option value="corner">${t('Esquina 90° · ensayo','90° corner · experiment')}</option></select></label><button type="button" class="pill twin-reset">${t('Isométrica','Isometric')}</button><button type="button" class="pill twin-floor">${t('Planta','Floor plan')}</button><button type="button" class="pill twin-front">${t('De frente','Front view')}</button><button type="button" class="pill twin-observe">${t('Punto de observación','Observation point')}</button><button type="button" class="pill twin-near" aria-label="${t('Acercar','Zoom in')}">＋</button><button type="button" class="pill twin-far" aria-label="${t('Alejar','Zoom out')}">−</button><label>${t('Luz','Light')} <select id="twin-light"><option value="day">${t('Día','Day')}</option><option value="sunset">${t('Atardecer','Sunset')}</option><option value="night">${t('Noche','Night')}</option></select></label></div>
  <div class="twin-observer" hidden><label>${t('Altura (m)','Height (m)')} <input id="twin-eye" type="number" min="1.2" max="2.2" step=".05" value="1.65"></label><label>${t('Distancia (m)','Distance (m)')} <input id="twin-distance" type="number" min="1.5" max="3.6" step=".1" value="3"></label><label>${t('Lateral (m)','Lateral (m)')} <input id="twin-lateral" type="number" min="-2" max="2" step=".1" value="0"></label><span>${t('Perspectiva · FOV 55° · punto fijo','Perspective · FOV 55° · fixed point')}</span></div>
  <div class="twin-stage" tabindex="0" role="img" aria-label="${t('Estanco Better isométrico con el formato adaptado en sus pantallas','Isometric Better shop with adapted content on its screens')}"></div>
  <p class="twin-status" role="status" aria-live="polite"></p><footer>${t('Arrastra para orbitar · rueda/pellizco para acercar · Shift + arrastrar para desplazar · flechas para girar · Esc para volver','Drag to orbit · wheel/pinch to zoom · Shift + drag to pan · arrows to rotate · Esc to return')}<br>${t('Referencia Xtanco de Stock; interior representativo, no levantamiento del estanco elegido. La esquina es un ensayo virtual; no modifica la exportación ni genera una anamorfosis.','Stock Xtanco reference; representative interior, not a scan of the selected shop. The corner is a virtual experiment; it does not change exports or generate an anamorphic warp.')}</footer>`;
  document.body.append(modal);const $=s=>modal.querySelector(s),stage=$('.twin-stage'),shop=$('#twin-shop'),status=$('.twin-status');
  let pending,built=null,active=null,geometry=null,revision=0,ctl=null,last=0,focus=null,view='home';
  const buttons=['.twin-reset','.twin-floor','.twin-front','.twin-observe','.twin-near','.twin-far'];
  function controls(on){for(const q of [...buttons,'#twin-scenario','#twin-light'])$(q).disabled=!on;}
  function clean(){ctl?.abort();ctl=null;built?.dispose();built=null;active=null;geometry=null;stage.replaceChildren();controls(false);}
  function close(){revision++;ctl?.abort();h.end?.();if(modal.open)modal.close();}
  modal.addEventListener('close',()=>{revision++;h.end?.();clean();focus?.focus();});modal.addEventListener('cancel',()=>{ctl?.abort();h.end?.();});$('.twin-close').onclick=close;
  function cameraChanged(state){stage.dataset.projection=state.projection;stage.dataset.view=state.mode;$('.twin-observer').hidden=state.mode!=='observer';}
  function preset(name){if(!built)return;view=name;if(name==='home')built.home();else if(name==='front')built.front();else built.viewer.preset(name);$('.twin-observer').hidden=true;draw(true);}
  $('.twin-reset').onclick=()=>preset('home');$('.twin-floor').onclick=()=>preset('floor');$('.twin-front').onclick=()=>preset('front');
  function observe(){if(!built)return;try{built.observe({height:Number($('#twin-eye').value),distance:Number($('#twin-distance').value),lateral:Number($('#twin-lateral').value)});view='observer';draw(true);}catch(_){status.textContent=t('El punto requiere altura 1,2–2,2 m, distancia 1,5–3,6 m y lateral −2–2 m.','Point requires height 1.2–2.2 m, distance 1.5–3.6 m and lateral −2–2 m.');}}
  $('.twin-observe').onclick=observe;for(const q of ['#twin-eye','#twin-distance','#twin-lateral'])$(q).onchange=observe;
  $('.twin-near').onclick=()=>{built?.viewer.zoomBy(1.25);draw(true);};$('.twin-far').onclick=()=>{built?.viewer.zoomBy(.8);draw(true);};
  stage.onkeydown=e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();built?.viewer.rotate(e.key==='ArrowLeft'?1:-1);draw(true);}};
  const observer=new ResizeObserver(()=>{if(built&&modal.open){built.viewer.resize(stage.clientWidth,stage.clientHeight);draw(true);}});observer.observe(stage);
  function description(){if(!built)return;const wall=geometry.pared,corner=$('#twin-scenario').value==='corner';$('#twin-format').textContent=`${active.nombre} · ${wall.ancho}×${wall.alto} · ${geometry.segments.length} ${t('pantallas','screens')} · ${t('Better · modelo Xtanco','Better · Xtanco model')}`;
    status.textContent=[t('Referencia Better · tamaño de ensayo ','Better reference · trial size ')+`${built.placement.width.toFixed(2)}×${built.placement.height.toFixed(2)} m`,corner?t('Pared doblada a 90° para probar el contenido desde el observador; comprueba sus costuras.','Wall folded at 90° to test content from the observer; check its seams.'):'',...geometry.warnings].filter(Boolean).join(' · ');
    stage.dataset.format=active.id;stage.dataset.screens=String(geometry.segments.length);stage.dataset.surfaces=String(built.surfaces);stage.dataset.scenario=corner?'corner':'flat';stage.dataset.quality='better';stage.dataset.asset=built.reference.assetId;
  }
  $('#twin-scenario').onchange=()=>{if(!built)return;const previous=view;built.setLayout($('#twin-scenario').value);$('#twin-lateral').value=$('#twin-scenario').value==='corner'?'1':'0';description();if(previous==='observer')observe();else preset('home');};
  $('#twin-light').onchange=()=>{built?.viewer.setLighting($('#twin-light').value);draw(true);};shop.onchange=()=>h.selectShop?.(shop.value);
  function draw(force=false){if(!modal.open||!built||!active)return;const now=performance.now();if(!force&&now-last<40)return;last=now;built.draw(cv=>h.draw(cv,active,h.background(active)?.el));}
  async function open(f){if(!h.ready())return;const mine=++revision;focus=document.activeElement;clean();modal.showModal();h.start?.(f);ctl=new AbortController();const signal=ctl.signal;status.textContent=t('Cargando estanco Better de Stock…','Loading Better shop from Stock…');
    const shops=h.shops()||[];shop.replaceChildren(...(shops.length?shops:[{id:'studio-demo',nombre:t('Estanco · demo','Shop · demo')}]).map(s=>new Option(s.nombre,s.id)));if(shops.some(s=>s.id===h.shop()))shop.value=h.shop();shop.disabled=shops.length<2;
    $('#twin-scenario').value='flat';$('#twin-light').value='day';$('#twin-eye').value='1.65';$('#twin-distance').value='3';$('#twin-lateral').value='0';$('.twin-observer').hidden=true;
    try{const {createBetterTwin}=await(pending||=import('./gemelo-better.mjs'));if(mine!==revision||!modal.open)return;
      const cv=document.createElement('canvas');cv.tabIndex=0;cv.setAttribute('aria-label',t('Estanco Better 3D interactivo','Interactive Better 3D shop'));stage.append(cv);
      geometry=twinGeometry(f,h.destino(f));const next=await createBetterTwin({canvas:cv,geometry,signal,onCameraChange:cameraChanged});if(mine!==revision||!modal.open){next.dispose();return;}built=next;active=f;view='home';controls(true);built.viewer.resize(stage.clientWidth,stage.clientHeight);description();draw(true);$('.twin-close').focus();
    }catch(e){if(mine!==revision||signal.aborted)return;h.end?.();clean();status.textContent=t('No se pudo cargar la referencia Better. Comprueba la conexión y WebGL; cierra y vuelve a abrir.','Could not load Better reference. Check connection and WebGL; close and reopen.');console.error('Studio Better twin:',e);}
  }
  function button(f){const b=document.createElement('button');b.type='button';b.className='pill view-twin';b.textContent=`▣ ${t('Ver en gemelo digital','View in digital twin')}`;b.setAttribute('aria-label',`${t('Ver en gemelo digital','View in digital twin')}: ${f.nombre}`);b.disabled=!h.ready();b.onclick=e=>{e.stopPropagation();open(f);};return b;}
  controls(false);return {button,open,draw,close,sync:()=>document.querySelectorAll('.view-twin').forEach(b=>b.disabled=!h.ready())};
}
