import {twinGeometry,localizedTwinWarnings} from './gemelo-core.mjs?v=studio-best-3';
import {TWIN_REFERENCES,recommendedReferenceId,referenceById} from './gemelo-catalog.mjs?v=studio-best-3';

// Editor owns media/time. A single loaded model serves all preview formats.
export function mountTwin(h){
  const t=h.t,modal=document.createElement('dialog');modal.className='adapter-twin';modal.setAttribute('aria-labelledby','twin-title');
  modal.innerHTML=`<header><div><h2 id="twin-title">${t('Gemelo digital · Estancos','Digital twin · Shops')}</h2><p id="twin-format"></p></div><button type="button" class="pill twin-close" aria-label="${t('Cerrar gemelo digital','Close digital twin')}">✕</button></header>
  <div class="twin-tools twin-formats"><label>${t('Formato','Format')} <select id="twin-format-select"></select></label><button class="pill twin-prev" aria-label="${t('Formato anterior','Previous format')}">←</button><span id="twin-progress"></span><button class="pill twin-next" aria-label="${t('Formato siguiente','Next format')}">→</button><button class="pill twin-tour" aria-pressed="false">▶ ${t('Recorrer formatos','Run format tour')}</button></div>
  <div class="twin-tools"><label>${t('Estanco','Shop')} <select id="twin-shop"></select></label><label>${t('Calidad','Quality')} <select id="twin-quality"><option value="best">Best</option><option value="better">Better</option></select></label><label>${t('Referencia','Reference')} <select id="twin-reference"><option value="automatic">${t('Automática · según formato','Automatic · by format')}</option></select></label></div>
  <div class="twin-tools twin-camera"><button type="button" class="pill twin-reset">${t('Isométrica','Isometric')}</button><button type="button" class="pill twin-floor">${t('Planta','Floor plan')}</button><button type="button" class="pill twin-front">${t('De frente','Front view')}</button><button type="button" class="pill twin-observe">${t('Punto de observación','Observation point')}</button><button type="button" class="pill twin-near" aria-label="${t('Acercar','Zoom in')}">＋</button><button type="button" class="pill twin-far" aria-label="${t('Alejar','Zoom out')}">−</button><label>${t('Luz','Light')} <select id="twin-light"><option value="day">${t('Día','Day')}</option><option value="sunset">${t('Atardecer','Sunset')}</option><option value="night">${t('Noche','Night')}</option></select></label></div>
  <div class="twin-observer" hidden><label>${t('Altura (m)','Height (m)')} <input id="twin-eye" type="number" min="1.2" max="2.2" step=".05" value="1.65"></label><label>${t('Distancia (m)','Distance (m)')} <input id="twin-distance" type="number" min="1.5" max="3.6" step=".1" value="3"></label><label>${t('Lateral (m)','Lateral (m)')} <input id="twin-lateral" type="number" min="-2" max="2" step=".1" value="0"></label><span>${t('Perspectiva · FOV 55° · punto fijo','Perspective · FOV 55° · fixed point')}</span></div>
  <div class="twin-stage" tabindex="0" role="img" aria-label="${t('Estanco isométrico con el formato adaptado en sus pantallas','Isometric shop with adapted content on its screens')}"></div>
  <p class="twin-status" role="status" aria-live="polite"></p><footer>${t('Arrastra para orbitar · rueda/pellizco para acercar · Shift + arrastrar para desplazar · Esc para volver','Drag to orbit · wheel/pinch to zoom · Shift + drag to pan · Esc to return')}<br>${t('Estancos de referencia: la selección OSM no es un levantamiento medido. Montajes, esquina y prisma LED son ensayos; no modifican la exportación ni generan anamorfosis.','Reference shops: OSM selection is not a measured survey. Mounts, corner and LED prism are trials; they do not change exports or generate anamorphic warps.')}</footer>`;
  document.body.append(modal);const $=s=>modal.querySelector(s),stage=$('.twin-stage'),shop=$('#twin-shop'),status=$('.twin-status'),formats=$('#twin-format-select'),reference=$('#twin-reference'),quality=$('#twin-quality');
  for(const r of TWIN_REFERENCES)reference.add(new Option(t(r.label.es,r.label.en),r.id));
  try{quality.value=localStorage.getItem('studio-twin-quality')==='better'?'better':'best';}catch(_){}
  let pending,built=null,active=null,geometry=null,revision=0,ctl=null,last=0,focus=null,view='home',list=[],tour=null,playback=false;
  const buttons=['.twin-reset','.twin-floor','.twin-front','.twin-observe','.twin-near','.twin-far','.twin-prev','.twin-next','.twin-tour'];
  function controls(on){for(const q of [...buttons,'#twin-format-select','#twin-reference','#twin-light','#twin-quality'])$(q).disabled=!on;$('.twin-prev').disabled=$('.twin-next').disabled=$('.twin-tour').disabled=!on||list.length<2;}
  function stopTour(){if(tour)clearInterval(tour);tour=null;$('.twin-tour').setAttribute('aria-pressed','false');$('.twin-tour').textContent=`▶ ${t('Recorrer formatos','Run format tour')}`;stage.dataset.tour='off';}
  function startMedia(){if(!playback){h.start?.(active);playback=true;}}
  function endMedia(){if(playback){h.end?.();playback=false;}}
  function clean(){ctl?.abort();ctl=null;built?.dispose();built=null;stage.replaceChildren();controls(false);}
  function close(){stopTour();revision++;ctl?.abort();endMedia();if(modal.open)modal.close();}
  modal.addEventListener('close',()=>{stopTour();revision++;endMedia();clean();active=null;geometry=null;focus?.focus();});modal.addEventListener('cancel',()=>{stopTour();ctl?.abort();endMedia();});$('.twin-close').onclick=close;
  stage.addEventListener('pointerdown',stopTour);
  stage.addEventListener('wheel',stopTour,{passive:true});
  function cameraChanged(state){stage.dataset.projection=state.projection;stage.dataset.view=state.mode;$('.twin-observer').hidden=state.mode!=='observer';}
  function preset(name){if(!built)return;view=name;if(name==='home')built.home();else if(name==='front')built.front();else built.viewer.preset(name);$('.twin-observer').hidden=true;draw(true);}
  for(const [q,name] of [['.twin-reset','home'],['.twin-floor','floor'],['.twin-front','front']])$(q).onclick=()=>{stopTour();preset(name);};
  function observe(){if(!built)return;try{built.observe({height:Number($('#twin-eye').value),distance:Number($('#twin-distance').value),lateral:Number($('#twin-lateral').value)});view='observer';draw(true);}catch(_){status.textContent=t('El punto requiere altura 1,2–2,2 m, distancia 1,5–3,6 m y lateral −2–2 m.','Point requires height 1.2–2.2 m, distance 1.5–3.6 m and lateral −2–2 m.');}}
  $('.twin-observe').onclick=()=>{stopTour();observe();};for(const q of ['#twin-eye','#twin-distance','#twin-lateral'])$(q).onchange=()=>{stopTour();observe();};
  $('.twin-near').onclick=()=>{stopTour();built?.viewer.zoomBy(1.25);draw(true);};$('.twin-far').onclick=()=>{stopTour();built?.viewer.zoomBy(.8);draw(true);};
  stage.onkeydown=e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();stopTour();built?.viewer.rotate(e.key==='ArrowLeft'?1:-1);draw(true);}};
  const observer=new ResizeObserver(()=>{if(built&&modal.open){built.viewer.resize(stage.clientWidth,stage.clientHeight);draw(true);}});observer.observe(stage);
  const referenceId=()=>reference.value==='automatic'?recommendedReferenceId(active):reference.value;
  function description(){if(!built)return;const p=built.placement,wall=geometry.pared,r=referenceById(p.referenceId),label=t(r.label.es,r.label.en),tier=built.quality==='best'?'Best':'Better';
    $('#twin-title').textContent=t('Gemelo digital · Estancos · ','Digital twin · Shops · ')+tier;
    $('#twin-format').textContent=`${active.nombre} · ${wall.ancho}×${wall.alto} · ${geometry.segments.length} ${t('pantallas','screens')} · ${label}`;
    status.textContent=[`${label} · ${p.width.toFixed(2)}×${p.height.toFixed(2)} m · ${p.faceCount>1?t('desarrollo desplegado de ensayo','unfolded trial dimensions'):t('medidas de ensayo','trial dimensions')}`,p.faceCount===4?t('Prisma de cuatro caras; el net del PDF no está confirmado.','Four-face prism; PDF net is unconfirmed.'):'',p.faceCount===2?t('Esquina 90°; comprueba las costuras desde el observador.','90° corner; check seams from the observer.'):'',...localizedTwinWarnings(geometry,t)].filter(Boolean).join(' · ');
    Object.assign(stage.dataset,{format:active.id,screens:String(geometry.segments.length),surfaces:String(built.surfaces),reference:p.referenceId,scenario:p.faceCount===2?'corner':p.faceCount===4?'prism':'flat',quality:built.quality,asset:built.reference.assetId,fixtureMoves:String(built.arrangements.length)});
    formats.value=active.id;$('#twin-progress').textContent=`${list.findIndex(f=>f.id===active.id)+1}/${list.length}`;
  }
  function chooseFormat(f){if(!built||!f)return;try{const next=twinGeometry(f,h.destino(f));built.setGeometry(next,{formatId:f.id,referenceId:reference.value==='automatic'?recommendedReferenceId(f):reference.value});active=f;geometry=next;view='home';$('#twin-lateral').value='0';description();draw(true);}catch(e){status.textContent=t('No se pudo montar este formato.','Could not mount this format.');console.error('Studio format trial:',e);stopTour();}}
  formats.onchange=()=>{stopTour();chooseFormat(list.find(f=>f.id===formats.value));};
  function nextFormat(direction=1){const i=list.findIndex(f=>f.id===active?.id);chooseFormat(list[(i+direction+list.length)%list.length]);}
  $('.twin-prev').onclick=()=>{stopTour();nextFormat(-1);};$('.twin-next').onclick=()=>{stopTour();nextFormat();};
  $('.twin-tour').onclick=()=>{if(tour){stopTour();return;}if(!built||list.length<2)return;reference.value='automatic';chooseFormat(active);$('.twin-tour').setAttribute('aria-pressed','true');$('.twin-tour').textContent=`⏸ ${t('Pausar recorrido','Pause format tour')}`;stage.dataset.tour='on';tour=setInterval(()=>{if(modal.open&&built)nextFormat();else stopTour();},8000);};
  reference.onchange=()=>{stopTour();if(!built)return;try{const previous=view;built.setLayout(referenceId());$('#twin-lateral').value='0';description();if(previous==='observer')observe();else preset('home');}catch(e){status.textContent=t('No se pudo montar esta referencia.','Could not mount this reference.');console.error('Studio reference trial:',e);}};
  $('#twin-light').onchange=()=>{stopTour();built?.viewer.setLighting($('#twin-light').value);draw(true);};shop.onchange=()=>{stopTour();h.selectShop?.(shop.value);};
  function draw(force=false){if(!modal.open||!built||!active)return;const now=performance.now();if(!force&&now-last<40)return;last=now;built.draw(cv=>h.draw(cv,active,h.background?.(active)?.el));}
  async function load(){startMedia();const mine=++revision,f=active;clean();ctl=new AbortController();const signal=ctl.signal;status.textContent=t('Cargando modelo de Stock · ','Loading Stock model · ')+quality.value;
    try{const {createRetailTwin}=await(pending||=import('./gemelo-better.mjs?v=studio-best-3'));if(mine!==revision||!modal.open)return;
      const cv=document.createElement('canvas');cv.tabIndex=0;cv.setAttribute('aria-label',t('Estanco 3D interactivo','Interactive 3D shop'));stage.append(cv);const g=twinGeometry(f,h.destino(f));
      const next=await createRetailTwin({canvas:cv,geometry:g,formatId:f.id,referenceId:referenceId(),quality:quality.value,signal,onCameraChange:cameraChanged});if(mine!==revision||!modal.open){next.dispose();return;}built=next;active=f;geometry=g;view='home';controls(true);built.viewer.resize(stage.clientWidth,stage.clientHeight);built.home();built.viewer.setLighting($('#twin-light').value);description();draw(true);$('.twin-close').focus();
    }catch(e){if(mine!==revision||signal.aborted)return;clean();endMedia();status.textContent=t('No se pudo cargar el modelo seleccionado. Comprueba la conexión/WebGL o elige Better.','Could not load the selected model. Check connection/WebGL or choose Better.');quality.disabled=false;console.error('Studio retail twin:',e);}}
  quality.onchange=()=>{stopTour();try{localStorage.setItem('studio-twin-quality',quality.value);}catch(_){}if(active)load();};
  function open(f){if(!h.ready())return;if(modal.open){stopTour();chooseFormat(f);return;}focus=document.activeElement;clean();active=f;const all=h.formats?.()||[f];list=all.some(x=>x.id===f.id)?all:[f,...all];formats.replaceChildren(...list.map(x=>new Option(x.nombre,x.id)));formats.value=f.id;reference.value='automatic';$('#twin-light').value='day';$('#twin-eye').value='1.65';$('#twin-distance').value='3';$('#twin-lateral').value='0';$('.twin-observer').hidden=true;stopTour();modal.showModal();startMedia();
    const shops=h.shops()||[];shop.replaceChildren(...(shops.length?shops:[{id:'studio-demo',nombre:t('Estanco · demo','Shop · demo')}]).map(s=>new Option(s.nombre,s.id)));if(shops.some(s=>s.id===h.shop()))shop.value=h.shop();shop.disabled=shops.length<2;load();}
  function button(f){const b=document.createElement('button');b.type='button';b.className='pill view-twin';b.textContent=`▣ ${t('Ver en gemelo digital','View in digital twin')}`;b.setAttribute('aria-label',`${t('Ver en gemelo digital','View in digital twin')}: ${f.nombre}`);b.disabled=!h.ready();b.onclick=e=>{e.stopPropagation();open(f);};return b;}
  controls(false);return {button,open,draw,close,sync:()=>document.querySelectorAll('.view-twin').forEach(b=>b.disabled=!h.ready())};
}
