import {INSTALLATIONS,DURATION,cue,drawNextStep,loadNextStepAssets,createClock} from './render.mjs';
const en=new URLSearchParams(location.search).get('lang')==='en'||document.documentElement.lang==='en',t=(a,b)=>en?b:a;
document.documentElement.lang=en?'en':'es';
const $=s=>document.querySelector(s),clock=createClock();let product,selected='landscape',tour=false,raf=0,last=-1,stopped=false;
$('#demo-title').textContent=t('Una tienda. Un pulso.','One store. One pulse.');$('#demo-subtitle').textContent=t('NEXT STEP · una campaña que se vive, desde la entrada hasta el fondo.','NEXT STEP · a campaign to experience, from entrance to rear.');
$('#twin-link').textContent=t('Ver en la tienda ↗','View in the store ↗');$('#twin-link').href='https://www.admira.store/xpacios/sneakerstore/?campaign=next-step&view=jordan&lang='+(en?'en':'es');
$('#creator-link').textContent=t('Volver a Creador','Back to Creator');$('#creator-link').href=(en?'/en/creador/':'/creador/')+'?lang='+(en?'en':'es');
$('#download-label').textContent=t('Piezas listas para reproducir','Pieces ready to play');$('#demo-note').textContent=t('Demo del gemelo digital. Las medidas especiales son aproximadas; la activación y sincronización en la tienda física requieren comprobar sus players.','Digital twin demo. Special dimensions are approximate; physical store activation and synchronisation require checking its players.');
$('#contract-link').textContent=t('Campaña y mapa de pantallas ↓','Campaign and screen map ↓');
const canvases=new Map();
for(const i of INSTALLATIONS){const b=document.createElement('button');b.type='button';b.textContent=i.name[en?'en':'es'];b.dataset.installation=i.id;b.setAttribute('aria-pressed',String(i.id===selected));b.onclick=()=>{tour=false;$('#demo-tour').setAttribute('aria-pressed','false');selected=i.id;select();};$('#demo-tabs').append(b);const card=document.createElement('button');card.type='button';card.className='next-preview';card.setAttribute('aria-label',i.name[en?'en':'es']);card.onclick=()=>b.click();const canvas=document.createElement('canvas');canvas.width=Math.min(560,i.width);canvas.height=Math.round(i.height*canvas.width/i.width);canvas.setAttribute('aria-label',i.name[en?'en':'es']);const label=document.createElement('span');label.textContent=i.name[en?'en':'es'];card.append(canvas,label);$('#demo-overview').append(card);canvases.set(i.id,canvas);
 for(const s of i.screens){const a=document.createElement('a');a.href=`./media/${s.id}.mp4`;a.download=`next-step-${s.id}.mp4`;a.textContent=`${i.name[en?'en':'es']} · ${s.id}`;$('#demo-files').append(a);}}
function select(){const i=INSTALLATIONS.find(i=>i.id===selected);$('#demo-current').textContent=i.name[en?'en':'es'];$('#demo-stage').dataset.installation=i.id;$('#demo-hero').width=Math.min(1440,i.width);$('#demo-hero').height=Math.round(i.height*$('#demo-hero').width/i.width);for(const b of $('#demo-tabs').children)b.setAttribute('aria-pressed',String(b.dataset.installation===selected));}
function frame(now){if(stopped)return;raf=requestAnimationFrame(frame);if(document.hidden||now-last<40)return;last=now;const seconds=clock.time();if(tour){const next=INSTALLATIONS[Math.floor(seconds/6)%INSTALLATIONS.length].id;if(next!==selected){selected=next;select();}}if(product){for(const i of INSTALLATIONS)drawNextStep(canvases.get(i.id),i,product,seconds,en);drawNextStep($('#demo-hero'),INSTALLATIONS.find(i=>i.id===selected),product,seconds,en);}$('#demo-progress').value=seconds%DURATION;$('#demo-cue').textContent=cue(seconds,en).title;$('#demo-clock').textContent=String(Math.floor(seconds%DURATION)).padStart(2,'0')+' / 32';}
function pause(){clock.pause();$('#demo-state').textContent=t('Ⅱ Campaña pausada','Ⅱ Campaign paused');$('#demo-pause').textContent=t('▶ Continuar','▶ Resume');}
function play(){clock.play();$('#demo-state').textContent=t('● Campaña en directo','● Live campaign');$('#demo-pause').textContent=t('Ⅱ Pausar','Ⅱ Pause');}
$('#demo-pause').textContent=t('Ⅱ Pausar','Ⅱ Pause');$('#demo-pause').onclick=()=>clock.paused?play():pause();$('#demo-restart').textContent=t('↺ Desde el principio','↺ Restart');$('#demo-restart').onclick=()=>clock.restart();$('#demo-tour').textContent=t('Recorrer pantallas','Tour the screens');$('#demo-tour').onclick=()=>{tour=!tour;$('#demo-tour').setAttribute('aria-pressed',String(tour));};
window.NextStepDemo={run(args=''){const cmd=args.trim().toLowerCase();if(/^(pause|pausa|pausar)$/.test(cmd))pause();else if(/^(stop|parar|detener)$/.test(cmd)){pause();clock.restart();}else if(/^(restart|reiniciar)$/.test(cmd))clock.restart();else if(/^(tour|recorrer)$/.test(cmd)){tour=true;$('#demo-tour').setAttribute('aria-pressed','true');play();}else play();return 'NEXT STEP · '+t('7 configuraciones · 13 piezas · reloj compartido','7 configurations · 13 pieces · shared clock');}};
select();try{product=await loadNextStepAssets();$('#demo-state').textContent=t('● Campaña en directo','● Live campaign');frame(0);}catch{$('#demo-state').textContent=t('No se pudo cargar la campaña. Recarga para reintentar.','Campaign could not load. Reload to retry.');}
window.addEventListener('pagehide',()=>{stopped=true;cancelAnimationFrame(raf);},{once:true});
